/* AUTO-GENERATED by tools/release.mjs. Do not edit manually. */
window.SKYWARD_BUILD_INFO = Object.freeze({
  "product": "Skyward Control",
  "version": "1.12.0",
  "phase": "F12",
  "phaseName": "Modelo Realista de Aeronaves",
  "channel": "alpha",
  "build": "SC-1.12.0-F12-20260618-1138",
  "builtAt": "2026-06-18 11:38 BRT",
  "builtAtIso": "2026-06-18T11:38:16-03:00",
  "schema": 3,
  "contractSchema": 2,
  "testSchema": 3,
  "saveVaultSchema": 1,
  "pwaSchema": 1,
  "cacheSchema": 1,
  "uxSchema": 1,
  "desktopSchema": 1,
  "accessibilitySchema": 1,
  "replaySchema": 1,
  "aircraftPerformanceSchema": 1,
  "target": "Mobile-first / Tablet / Desktop"
});
