/* AUTO-GENERATED by tools/build-pwa.mjs. Do not edit manually. */
'use strict';
const PWA_META=Object.freeze({"schema":1,"cacheSchema":1,"build":"SC-1.40.0-F40-20260622-1320","cacheName":"skyward-control-1-sc-1.40.0-f40-20260622-1320"});
const CORE_ASSETS=Object.freeze([
  "./assets/backgrounds/BG_AIRPORT_DAY_CLEAR_V1.png",
  "./assets/backgrounds/BG_AIRPORT_NIGHT_RAIN_V1.png",
  "./assets/backgrounds/BG_CONTROL_TOWER_REALISTIC_V1.png",
  "./assets/characters/CHAR_CONTROLLER_FEMALE01_V1.png",
  "./assets/characters/CHAR_CONTROLLER_MALE01_V1.png",
  "./assets/icons/icon-180.png",
  "./assets/icons/icon-192.png",
  "./assets/icons/icon-512.png",
  "./assets/icons/icon-maskable-512.png",
  "./assets/maps/MAP_KATL_AIRPORT_CLEAN_V1.png",
  "./assets/radar/RADAR_BASE_CLEAN_V1.png",
  "./assets/ui/UI_PANEL_DARK_GLASS_V1.png",
  "./build-info.js",
  "./data/aircraft-performance.json",
  "./data/aircraft.json",
  "./data/airline-operations.json",
  "./data/airport-authority.json",
  "./data/airport-graphs.json",
  "./data/airports.json",
  "./data/career-ratings.json",
  "./data/control-room-ranking.json",
  "./data/crisis-command-center.json",
  "./data/economy-contracts.json",
  "./data/environment-sustainability.json",
  "./data/gold-master-package.json",
  "./data/incident-playbooks.json",
  "./data/infrastructure-expansion.json",
  "./data/international-campaign.json",
  "./data/multi-airport-network.json",
  "./data/network-flow-slots.json",
  "./data/passenger-reputation.json",
  "./data/post-gold-master-publishing.json",
  "./data/post-publish-healthcheck.json",
  "./data/procedures-f16.json",
  "./data/public-ops-feedback.json",
  "./data/release-candidate-qa.json",
  "./data/revenue-management.json",
  "./data/safety-compliance-center.json",
  "./data/surface-hotspots.json",
  "./data/training-academy-scenarios.json",
  "./data/training-coach-debriefing.json",
  "./data/ux-polish-presets.json",
  "./data/weather-profiles.json",
  "./data/workforce-staffing.json",
  "./index.html",
  "./main.js",
  "./manifest.webmanifest",
  "./style.css",
  "./pwa-cache-manifest.json"
]);
const CACHE_PREFIX='skyward-control-';
const NAVIGATION_FALLBACK='./index.html';
async function openCurrentCache(){return caches.open(PWA_META.cacheName);}
async function precache(){const cache=await openCurrentCache();await cache.addAll(CORE_ASSETS);return true;}
self.addEventListener('install',event=>{event.waitUntil((async()=>{await precache();if(!self.registration.active)await self.skipWaiting();})());});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const names=await caches.keys();await Promise.all(names.filter(name=>name.startsWith(CACHE_PREFIX)&&name!==PWA_META.cacheName).map(name=>caches.delete(name)));await self.clients.claim();})());});
self.addEventListener('message',event=>{const data=event.data||{};if(data.type==='SKIP_WAITING')self.skipWaiting();if(data.type==='GET_VERSION'){const reply={type:'PWA_VERSION',build:PWA_META.build,cacheName:PWA_META.cacheName,cacheReady:true};if(event.source&&event.source.postMessage)event.source.postMessage(reply);}});
async function navigationResponse(request){const cache=await openCurrentCache();try{const response=await fetch(request);if(response&&response.ok)cache.put(NAVIGATION_FALLBACK,response.clone());return response;}catch(_error){return (await cache.match(request,{ignoreSearch:true}))||(await cache.match(NAVIGATION_FALLBACK))||(await cache.match('./'));}}
async function cachedResponse(request){const cache=await openCurrentCache();const cached=await cache.match(request,{ignoreSearch:false});if(cached)return cached;try{const response=await fetch(request);if(response&&response.ok&&new URL(request.url).origin===self.location.origin)cache.put(request,response.clone());return response;}catch(_error){return new Response('',{status:503,statusText:'Offline'});}}
self.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.mode==='navigate'){event.respondWith(navigationResponse(request));return;}event.respondWith(cachedResponse(request));});
