import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE27_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE27_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/public-ops-feedback.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F27',metadata.version==='1.27.0'&&metadata.phase==='F27');check('build oficial F27',/^SC-1\.27\.0-F27-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('public ops schema 1',metadata.publicOpsSchema===1&&config.publicOpsSchema===1);check('canal public-ops',metadata.channel==='public-ops'&&config.channel==='public-ops');check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1&&metadata.releaseCandidateSchema===1&&metadata.goldMasterSchema===1&&metadata.postGoldMasterSchema===1&&metadata.postPublishHealthSchema===1);}
if(order&&runtime){check('arquitetura geração 27',runtime.architectureGeneration===27);check('36 módulos oficiais',order.modules.length>=36&&runtime.moduleCount===order.modules.length);check('módulo public ops antes de tráfego',order.modules.findIndex(m=>m.file==='30-public-ops-feedback.js')>=0&&order.modules.findIndex(m=>m.file==='30-public-ops-feedback.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F27 registrada',String(runtime.strategy).includes('public-ops-feedback'));}
const source=read('src/runtime/30-public-ops-feedback.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F27 integrado',source.includes('PUBLIC_OPS_CATALOG')&&source.includes('window.SKYWARD_PUBLIC_OPS=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.feedbackCategories?.length>=6&&catalog.telemetryCounters?.length>=6&&catalog.hotfixTemplates?.length>=5);
check('F27 conectado ao início',traffic.includes('initializePublicOps')&&traffic.includes('startTurn'));
check('UI final mostra Public Ops',ui.includes('Public Ops')&&ui.includes('Ops Score'));
check('CSS painel Public Ops',style.includes('.public-ops-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 30-public-ops-feedback')&&bundle.includes('SKYWARD_PUBLIC_OPS'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/public-ops-feedback.json'));
check('docs F27 existem',fs.existsSync(path.join(root,'docs/PUBLIC_OPS_FEEDBACK_F27.md'))&&fs.existsSync(path.join(root,'docs/FEEDBACK_PUBLICO_F27.md'))&&fs.existsSync(path.join(root,'docs/HOTFIX_PLANNER_F27.md'))&&fs.existsSync(path.join(root,'docs/TELEMETRIA_OFFLINE_F27.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
check('hotfix templates úteis',catalog.hotfixTemplates.some(t=>t.id==='PWA_CACHE_PATCH')&&catalog.hotfixTemplates.some(t=>t.id==='MOBILE_SCROLL_PATCH'));
const run=spawnSync(process.execPath,['tests/phase27-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F27 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=16,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F27 disponíveis',['test:unit:f27','test:browser:f27','test:phase27'].every(k=>pkg.scripts?.[k]));check('npm test contém F27',String(pkg.scripts.test).includes('test:unit:f27')&&String(pkg.scripts.test).includes('test:browser:f27')&&String(pkg.scripts.test).includes('test:phase27'));}
const required=['src/runtime/30-public-ops-feedback.js','data/public-ops-feedback.json','tests/phase27-unit-tests.mjs','tests/phase27-browser-tests.py','tests/phase27-audit.mjs','docs/PUBLIC_OPS_FEEDBACK_F27.md','docs/FEEDBACK_PUBLICO_F27.md','docs/HOTFIX_PLANNER_F27.md','docs/TELEMETRIA_OFFLINE_F27.md','docs/FASE_27_CHECKLIST.md','docs/FASE_27_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE27_UNIT_TESTS.json','audit/PHASE27_BROWSER_TESTS.json'];check('artefatos F27 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F27 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
