import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE13_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE13_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/airport-graphs.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F13',metadata.version==='1.13.0'&&metadata.phase==='F13');check('build oficial F13',/^SC-1\.13\.0-F13-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('airport surface schema 1',metadata.airportSurfaceSchema===1&&config.airportSurfaceSchema===1);check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1);check('metadados sincronizados',['product','version','phase','phaseName','channel','saveSchema','contractSchema','testSchema','saveVaultSchema','pwaSchema','cacheSchema','uxSchema','desktopSchema','accessibilitySchema','replaySchema','aircraftPerformanceSchema','airportSurfaceSchema','target','build','builtAt','builtAtIso'].every(k=>metadata[k]===config[k]));}
if(order&&runtime){check('arquitetura geração 13',runtime.architectureGeneration===13);check('22 módulos oficiais',order.modules.length>=22&&runtime.moduleCount===order.modules.length);check('módulo surface antes de tráfego',order.modules.findIndex(m=>m.file==='16-airport-surface-graph.js')>=0&&order.modules.findIndex(m=>m.file==='16-airport-surface-graph.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F13 registrada',String(runtime.strategy).includes('airport-surface-graph'));}
const source=read('src/runtime/16-airport-surface-graph.js'),bundle=read('main.js'),render=read('src/runtime/08-radar-rendering.js'),sim=read('src/runtime/07-simulation-safety.js'),traffic=read('src/runtime/06-traffic-requests.js');
check('módulo F13 integrado',source.includes('AIRPORT_SURFACE_CATALOG')&&source.includes('window.SKYWARD_AIRPORT_SURFACE=Object.freeze'));
check('catálogo data-driven completo',catalog?.schema===1&&Object.keys(catalog.airports||{}).length>=5);
check('aeroportos-chave presentes',['SBGR','SBSP','SBKP','SBBR','KATL'].every(t=>JSON.stringify(catalog.airports).includes(t)));
check('grafo conectado ao tráfego',traffic.includes('applyAirportSurfaceGraph')&&traffic.includes('gateId'));
check('simulação usa rotas de solo e vacate',sim.includes('assignDepartureSurfaceRoute')&&sim.includes("p.status==='VACATE'"));
check('render desenha taxiways e pistas secundárias',render.includes('graph?.taxiways')&&render.includes('secondaryRunways'));
check('bundle sincronizado',bundle.includes('@skyward-module 16-airport-surface-graph')&&bundle.includes('SKYWARD_AIRPORT_SURFACE'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/airport-graphs.json'));
const run=spawnSync(process.execPath,['tests/phase13-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F13 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=18,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=18,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));check('taxiways comprovadas',(browser.checks||[]).some(c=>c.ok&&c.name.includes('taxiways')));}
if(pkg){check('scripts F13 disponíveis',['test:unit:f13','test:browser:f13','test:phase13'].every(k=>pkg.scripts?.[k]));check('npm test contém F13',String(pkg.scripts.test).includes('test:unit:f13')&&String(pkg.scripts.test).includes('test:browser:f13')&&String(pkg.scripts.test).includes('test:phase13'));}
const release=read('tools/release.mjs');check('pipeline executa F13',release.includes('tests/phase13-unit-tests.mjs')&&release.includes('tests/phase13-browser-tests.py')&&release.includes('tests/phase13-audit.mjs'));check('pacote revalida F13',release.lastIndexOf('tests/phase13-audit.mjs')>release.indexOf('writeManifest(stage)'));
const required=['src/runtime/16-airport-surface-graph.js','data/airport-graphs.json','tests/phase13-unit-tests.mjs','tests/phase13-browser-tests.py','tests/phase13-audit.mjs','docs/GRAFO_REALISTA_AEROPORTOS_F13.md','docs/FASE_13_CHECKLIST.md','docs/FASE_13_AUDITORIA.md','audit/PHASE13_UNIT_TESTS.json','audit/PHASE13_BROWSER_TESTS.json'];check('artefatos F13 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F13 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
