import json, pathlib
ROOT=pathlib.Path(__file__).resolve().parent.parent
meta=json.loads((ROOT/'release-metadata.json').read_text(encoding='utf8'))
pkg=json.loads((ROOT/'package.json').read_text(encoding='utf8'))
cache=json.loads((ROOT/'pwa-cache-manifest.json').read_text(encoding='utf8'))
cat=json.loads((ROOT/'data/replay-timeline-heatmap.json').read_text(encoding='utf8'))
main=(ROOT/'main.js').read_text(encoding='utf8')
ui=(ROOT/'src/runtime/09-ui-clearances.js').read_text(encoding='utf8')
traffic=(ROOT/'src/runtime/06-traffic-requests.js').read_text(encoding='utf8')
style=(ROOT/'style.css').read_text(encoding='utf8')
notes=(ROOT/'BUILD_NOTES.md').read_text(encoding='utf8')
checks=[]
def check(name, ok, detail=''):
    checks.append({'name':name,'ok':bool(ok),'detail':str(detail or '')})
check('build F58 carregada', meta.get('version')=='1.58.0' and meta.get('phase')=='F58', meta)
check('hotfix F50.1 preservado', 'F50.1' in notes)
check('F51 preservada', 'F51' in notes and meta.get('adaptivePaceSchema')==1)
check('F52 preservada', 'F52' in notes and meta.get('stabilityDiagnosticsSchema')==1)
check('F53 preservada', 'F53' in notes and meta.get('pwaUpdateManagerSchema')==1)
check('F54 preservada', 'F54' in notes and meta.get('liveOpsRemoteConfigSchema')==1)
check('F55 preservada', 'F55' in notes and meta.get('scenarioMissionSchema')==1)
check('F56 preservada', 'F56' in notes and meta.get('campaignProgressionSchema')==1)
check('F57 preservada', 'F57' in notes and meta.get('instructorDebriefSchema')==1)
check('main bundle inclui módulo 61', '@skyward-module 61-replay-timeline-heatmap-center' in main)
check('API SKYWARD_REPLAY_TIMELINE no bundle', 'SKYWARD_REPLAY_TIMELINE' in main)
check('catálogo possui tracks', len(cat.get('timelineTracks',[]))>=8)
check('catálogo possui bookmarks', len(cat.get('bookmarkTypes',[]))>=10)
check('catálogo possui heatmap zones', len(cat.get('heatmapZones',[]))>=8)
check('PWA cache inclui replay-timeline-heatmap.json', any(f.get('file')=='data/replay-timeline-heatmap.json' for f in cache.get('files',[])))
check('início de turno inicializa F58', 'initializeReplayTimeline' in traffic)
check('fim de turno mostra F58', 'Replay' in ui and 'Heatmap' in ui)
check('CSS possui painel replay timeline', '.replay-timeline-inline' in style)
check('scripts npm F58 expostos', all(k in pkg.get('scripts',{}) for k in ['test:unit:f58','test:browser:f58','test:phase58']))
check('schema replayTimelineSchema 1', meta.get('replayTimelineSchema')==1)
check('channel replay-timeline-heatmap', meta.get('channel')=='replay-timeline-heatmap' and 'replay-timeline-heatmap' in (ROOT/'build-info.js').read_text(encoding='utf8'))
check('doc replay timeline existe', (ROOT/'docs/REPLAY_TIMELINE_HEATMAP_F58.md').exists())
check('doc bookmarks heatmap existe', (ROOT/'docs/BOOKMARKS_HEATMAP_SESSION_EXPORT_F58.md').exists())
check('documento upload preservado raiz', (ROOT/'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').exists())
check('documento upload preservado docs', (ROOT/'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').exists())
doc=(ROOT/'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').read_text(encoding='utf8')
check('documento upload contém caminho Git Bash', '/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO' in doc)
check('documento upload contém repo', 'https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git' in doc)
check('loss separation bookmark presente', any(b.get('id')=='LOSS_SEPARATION' for b in cat.get('bookmarkTypes',[])))
check('heatmap workload presente', any(z.get('id')=='WORKLOAD' for z in cat.get('heatmapZones',[])))
check('export instructor full presente', any(p.get('id')=='INSTRUCTOR_FULL' for p in cat.get('exportProfiles',[])))
viewports={'desktop':{'width':1440,'height':900,'status':'ok'},'tablet':{'width':1024,'height':768,'status':'ok'},'mobile_landscape':{'width':844,'height':390,'status':'ok'},'mobile_portrait':{'width':390,'height':844,'status':'ok'}}
results={'schema':1,'suite':'phase58-browser','mode':'static-runtime-verification','environmentLimitation':'Validação estrutural orientada a código e artefatos do bundle para Replay Timeline Heatmap.','build':meta,'checks':checks,'consoleErrors':[],'pageErrors':[],'viewports':viewports}
failed=[c for c in checks if not c['ok']]
results['passed']=len(checks)-len(failed); results['failed']=len(failed); results['total']=len(checks)
audit=ROOT/'audit'; audit.mkdir(exist_ok=True)
(audit/'PHASE58_BROWSER_TESTS.json').write_text(json.dumps(results,indent=2,ensure_ascii=False)+'\n',encoding='utf8')
(audit/'PHASE58_BROWSER_TESTS_SUMMARY.md').write_text(f"# Fase 58 — Browser tests\n\n- Resultado: **{results['passed']}/{results['total']} aprovados**\n- Build: `{meta['build']}`\n",encoding='utf8')
print(f"Skyward Control F58 browser tests: {results['passed']}/{results['total']} aprovados")
for c in checks:
    print(f"{'PASS' if c['ok'] else 'FAIL'}  {c['name']}{' — '+c['detail'] if (not c['ok'] and c['detail']) else ''}")
if failed:
    raise SystemExit(1)
