import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE31_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE31_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/airline-operations.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F31',metadata.version==='1.31.0'&&metadata.phase==='F31');check('build oficial F31',/^SC-1\.31\.0-F31-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('airline ops schema 1',metadata.airlineOpsSchema===1&&config.airlineOpsSchema===1);check('canal airline-operations',metadata.channel==='airline-operations'&&config.channel==='airline-operations');check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1&&metadata.releaseCandidateSchema===1&&metadata.goldMasterSchema===1&&metadata.postGoldMasterSchema===1&&metadata.postPublishHealthSchema===1&&metadata.publicOpsSchema===1&&metadata.trainingAcademySchema===1&&metadata.trainingCoachSchema===1&&metadata.internationalCampaignSchema===1);}
if(order&&runtime){check('arquitetura geração 31',runtime.architectureGeneration===31);check('40 módulos oficiais',order.modules.length>=40&&runtime.moduleCount===order.modules.length);check('módulo airline antes de tráfego',order.modules.findIndex(m=>m.file==='34-airline-operations-center.js')>=0&&order.modules.findIndex(m=>m.file==='34-airline-operations-center.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F31 registrada',String(runtime.strategy).includes('airline-operations-center'));}
const source=read('src/runtime/34-airline-operations-center.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F31 integrado',source.includes('AIRLINE_OPS_CATALOG')&&source.includes('window.SKYWARD_AIRLINE_OPS=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.airlines?.length>=5&&catalog.routeBanks?.length>=4&&catalog.slaMetrics?.length>=5);
check('F31 conectado ao início',traffic.includes('initializeAirlineOps'));
check('UI final mostra Airline Ops',ui.includes('Airline Ops')&&ui.includes('SLA Cias'));
check('CSS painel Airline',style.includes('.airline-ops-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 34-airline-operations-center')&&bundle.includes('SKYWARD_AIRLINE_OPS'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/airline-operations.json'));
check('docs F31 existem',fs.existsSync(path.join(root,'docs/AIRLINE_OPS_CENTER_F31.md'))&&fs.existsSync(path.join(root,'docs/COMPANHIAS_MALHA_SLA_F31.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
check('airline ops possui KATL/cargo',catalog.airlines.some(a=>a.id==='DAL')&&catalog.demandProfiles.some(d=>d.id==='CARGO_PEAK'));
const run=spawnSync(process.execPath,['tests/phase31-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F31 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=15,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F31 disponíveis',['test:unit:f31','test:browser:f31','test:phase31'].every(k=>pkg.scripts?.[k]));check('npm test contém F31',String(pkg.scripts.test).includes('test:unit:f31')&&String(pkg.scripts.test).includes('test:browser:f31')&&String(pkg.scripts.test).includes('test:phase31'));}
const required=['src/runtime/34-airline-operations-center.js','data/airline-operations.json','tests/phase31-unit-tests.mjs','tests/phase31-browser-tests.py','tests/phase31-audit.mjs','docs/AIRLINE_OPS_CENTER_F31.md','docs/COMPANHIAS_MALHA_SLA_F31.md','docs/FASE_31_CHECKLIST.md','docs/FASE_31_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE31_UNIT_TESTS.json','audit/PHASE31_BROWSER_TESTS.json'];check('artefatos F31 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F31 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
