import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE34_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE34_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/safety-compliance-center.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F34',metadata.version==='1.34.0'&&metadata.phase==='F34');check('build oficial F34',/^SC-1\.34\.0-F34-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('safety compliance schema 1',metadata.safetyComplianceSchema===1&&config.safetyComplianceSchema===1);check('canal safety-compliance',metadata.channel==='safety-compliance'&&config.channel==='safety-compliance');check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1&&metadata.releaseCandidateSchema===1&&metadata.goldMasterSchema===1&&metadata.postGoldMasterSchema===1&&metadata.postPublishHealthSchema===1&&metadata.publicOpsSchema===1&&metadata.trainingAcademySchema===1&&metadata.trainingCoachSchema===1&&metadata.internationalCampaignSchema===1&&metadata.airlineOpsSchema===1&&metadata.airportAuthoritySchema===1&&metadata.crisisCommandSchema===1);}
if(order&&runtime){check('arquitetura geração 34',runtime.architectureGeneration===34);check('43 módulos oficiais',order.modules.length>=43&&runtime.moduleCount===order.modules.length);check('módulo safety antes de tráfego',order.modules.findIndex(m=>m.file==='37-safety-compliance-center.js')>=0&&order.modules.findIndex(m=>m.file==='37-safety-compliance-center.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F34 registrada',String(runtime.strategy).includes('safety-compliance-center'));}
const source=read('src/runtime/37-safety-compliance-center.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F34 integrado',source.includes('SAFETY_COMPLIANCE_CATALOG')&&source.includes('window.SKYWARD_SAFETY_COMPLIANCE=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.auditDomains?.length>=7&&catalog.correctiveActions?.length>=5&&catalog.rootCauses?.length>=5);
check('F34 conectado ao início',traffic.includes('initializeSafetyCompliance'));
check('UI final mostra Safety SMS',ui.includes('Safety SMS')&&ui.includes('Achados SMS'));
check('CSS painel Safety',style.includes('.safety-compliance-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 37-safety-compliance-center')&&bundle.includes('SKYWARD_SAFETY_COMPLIANCE'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/safety-compliance-center.json'));
check('docs F34 existem',fs.existsSync(path.join(root,'docs/SAFETY_COMPLIANCE_CENTER_F34.md'))&&fs.existsSync(path.join(root,'docs/AUDITORIA_CAUSA_RAIZ_CAP_F34.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
check('safety possui runway/CAP',catalog.auditDomains.some(d=>d.id==='RUNWAY_SAFETY')&&catalog.correctiveActions.some(c=>c.id==='CAP_TRAINING'));
const run=spawnSync(process.execPath,['tests/phase34-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F34 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=15,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F34 disponíveis',['test:unit:f34','test:browser:f34','test:phase34'].every(k=>pkg.scripts?.[k]));check('npm test contém F34',String(pkg.scripts.test).includes('test:unit:f34')&&String(pkg.scripts.test).includes('test:browser:f34')&&String(pkg.scripts.test).includes('test:phase34'));}
const required=['src/runtime/37-safety-compliance-center.js','data/safety-compliance-center.json','tests/phase34-unit-tests.mjs','tests/phase34-browser-tests.py','tests/phase34-audit.mjs','docs/SAFETY_COMPLIANCE_CENTER_F34.md','docs/AUDITORIA_CAUSA_RAIZ_CAP_F34.md','docs/FASE_34_CHECKLIST.md','docs/FASE_34_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE34_UNIT_TESTS.json','audit/PHASE34_BROWSER_TESTS.json'];check('artefatos F34 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F34 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
