import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE19_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE19_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/incident-playbooks.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F19',metadata.version==='1.19.0'&&metadata.phase==='F19');check('build oficial F19',/^SC-1\.19\.0-F19-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('incident schema 1',metadata.incidentSchema===1&&config.incidentSchema===1);check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1);}
if(order&&runtime){check('arquitetura geração 19',runtime.architectureGeneration===19);check('28 módulos oficiais',order.modules.length>=28&&runtime.moduleCount===order.modules.length);check('módulo incidentes antes de tráfego',order.modules.findIndex(m=>m.file==='22-incident-emergency-director.js')>=0&&order.modules.findIndex(m=>m.file==='22-incident-emergency-director.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F19 registrada',String(runtime.strategy).includes('complex-operational-incidents'));}
const source=read('src/runtime/22-incident-emergency-director.js'),bundle=read('main.js'),sim=read('src/runtime/07-simulation-safety.js'),ui=read('src/runtime/09-ui-clearances.js'),econ=read('src/runtime/21-operational-economy.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F19 integrado',source.includes('INCIDENT_PLAYBOOK_CATALOG')&&source.includes('window.SKYWARD_INCIDENTS=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.incidentTypes?.length>=7&&Object.keys(catalog.agencies||{}).length>=8);
check('incidentes essenciais presentes',['BIRD_STRIKE','ENGINE_FAILURE','MEDICAL_EVAC','GEAR_UNSAFE','RUNWAY_FOD','BRAKE_FIRE','SECURITY_EVAC'].every(id=>catalog.incidentTypes.some(i=>i.id===id)));
check('incidentes conectados à simulação',sim.includes('incidentTick')&&sim.includes('maybeTriggerIncident'));
check('commandRisk consulta incidentes',sim.includes('incidentRiskForCommand'));
check('economia usa incidentes',econ.includes('incidentEconomicImpact'));
check('painel incidentes renderizado no início',traffic.includes('renderIncidentBoard'));
check('UI final mostra incidentes',ui.includes('Incidentes resolvidos')&&ui.includes('Falhas em incidentes'));
check('painel incidentes no CSS',style.includes('.incident-ops-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 22-incident-emergency-director')&&bundle.includes('SKYWARD_INCIDENTS'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/incident-playbooks.json'));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
const run=spawnSync(process.execPath,['tests/phase19-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F19 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=16,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F19 disponíveis',['test:unit:f19','test:browser:f19','test:phase19'].every(k=>pkg.scripts?.[k]));check('npm test contém F19',String(pkg.scripts.test).includes('test:unit:f19')&&String(pkg.scripts.test).includes('test:browser:f19')&&String(pkg.scripts.test).includes('test:phase19'));}
const required=['src/runtime/22-incident-emergency-director.js','data/incident-playbooks.json','tests/phase19-unit-tests.mjs','tests/phase19-browser-tests.py','tests/phase19-audit.mjs','docs/INCIDENTES_OPERACIONAIS_COMPLEXOS_F19.md','docs/FASE_19_CHECKLIST.md','docs/FASE_19_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE19_UNIT_TESTS.json','audit/PHASE19_BROWSER_TESTS.json'];check('artefatos F19 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F19 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
