import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const prepackage=process.argv.includes('--prepackage');const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE46_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE46_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/radio-phraseology.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F46',metadata.version==='1.46.0'&&metadata.phase==='F46');check('build oficial F46',/^SC-1\.46\.0-F46-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('radio phraseology schema 1',metadata.radioPhraseologySchema===1&&config.radioPhraseologySchema===1);check('canal radio-phraseology',metadata.channel==='radio-phraseology'&&config.channel==='radio-phraseology');check('aiCopilot preservado',metadata.aiCopilotSchema===1);}
if(order&&runtime){check('arquitetura geração 46',runtime.architectureGeneration===46);check('55 módulos oficiais',order.modules.length>=55&&runtime.moduleCount===order.modules.length);check('módulo radio antes de tráfego',order.modules.findIndex(m=>m.file==='49-radio-communications-phraseology-center.js')>=0&&order.modules.findIndex(m=>m.file==='49-radio-communications-phraseology-center.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F46 registrada',String(runtime.strategy).includes('radio-phraseology-vhf-readback-hearback-cpdlc'));}
const source=read('src/runtime/49-radio-communications-phraseology-center.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F46 integrado',source.includes('RADIO_PHRASEOLOGY_CATALOG')&&source.includes('window.SKYWARD_RADIO_PHRASEOLOGY=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.communicationDomains?.length>=7&&catalog.communicationIssues?.length>=7&&catalog.improvementPrograms?.length>=6);
check('F46 conectado início',traffic.includes('initializeRadioPhraseology'));check('UI final mostra Radio Ops',ui.includes('Radio Ops')&&ui.includes('Readback'));check('CSS painel Radio',style.includes('.radio-phraseology-inline'));check('bundle sincronizado',bundle.includes('@skyward-module 49-radio-communications-phraseology-center')&&bundle.includes('SKYWARD_RADIO_PHRASEOLOGY'));check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/radio-phraseology.json'));check('docs F46 existem',fs.existsSync(path.join(root,'docs/RADIO_PHRASEOLOGY_F46.md'))&&fs.existsSync(path.join(root,'docs/VHF_READBACK_CPDLC_F46.md')));check('upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));check('radio possui readback/CPDLC',catalog.communicationDomains.some(d=>d.id==='READBACK_ACCURACY')&&catalog.communicationDomains.some(d=>d.id==='CPDLC_TEXT'));
const run=spawnSync(process.execPath,['tests/phase46-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários executam novamente',run.status===0,(run.stderr||run.stdout).trim());if(unit&&metadata){check('relatório unitário pertence build',unit.build===metadata.build);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=10,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('browser pertence build',browser.build?.build===metadata.build);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0);}if(pkg){check('scripts F46 disponíveis',['test:unit:f46','test:browser:f46','test:phase46'].every(k=>pkg.scripts?.[k]));}
const required=['src/runtime/49-radio-communications-phraseology-center.js','data/radio-phraseology.json','tests/phase46-unit-tests.mjs','tests/phase46-browser-tests.py','tests/phase46-audit.mjs','docs/RADIO_PHRASEOLOGY_F46.md','docs/VHF_READBACK_CPDLC_F46.md','docs/FASE_46_CHECKLIST.md','docs/FASE_46_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE46_UNIT_TESTS.json','audit/PHASE46_BROWSER_TESTS.json'];check('artefatos F46 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F46 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
