import json, pathlib
ROOT=pathlib.Path(__file__).resolve().parent.parent
meta=json.loads((ROOT/'release-metadata.json').read_text(encoding='utf8'))
pkg=json.loads((ROOT/'package.json').read_text(encoding='utf8'))
cache=json.loads((ROOT/'pwa-cache-manifest.json').read_text(encoding='utf8'))
cat=json.loads((ROOT/'data/post-gold-master-publishing.json').read_text(encoding='utf8'))
main=(ROOT/'main.js').read_text(encoding='utf8')
ui=(ROOT/'src/runtime/09-ui-clearances.js').read_text(encoding='utf8')
traffic=(ROOT/'src/runtime/06-traffic-requests.js').read_text(encoding='utf8')
style=(ROOT/'style.css').read_text(encoding='utf8')
checks=[]
def check(name, ok, detail=''):
    checks.append({'name':name,'ok':bool(ok),'detail':str(detail or '')})
check('build F25 carregada', meta.get('version')=='1.25.0' and meta.get('phase')=='F25', meta)
check('main bundle inclui módulo 28', '@skyward-module 28-post-gold-master-publishing' in main)
check('API SKYWARD_POST_GOLD_MASTER no bundle', 'SKYWARD_POST_GOLD_MASTER' in main)
check('catálogo possui real device matrix', len(cat.get('realDeviceMatrix',[]))>=5)
check('catálogo possui screenshot plan', len(cat.get('screenshotPlan',[]))>=6)
check('catálogo possui bug triage', len(cat.get('bugTriage',[]))>=4)
check('catálogo possui publishing steps', len(cat.get('publishingSteps',[]))>=7)
check('PWA cache inclui post-gold-master-publishing.json', any(f.get('file')=='data/post-gold-master-publishing.json' for f in cache.get('files',[])))
check('início de turno inicializa Post-GM', 'initializePostGoldMasterPublishing' in traffic)
check('fim de turno mostra Post-GM', 'Publicação PWA' in ui and 'Post-GM Ready' in ui)
check('CSS possui painel Post-GM', '.post-gold-master-inline' in style)
check('scripts npm F25 expostos', all(k in pkg.get('scripts',{}) for k in ['test:unit:f25','test:browser:f25','test:phase25']))
check('schema postGoldMasterSchema 1', meta.get('postGoldMasterSchema')==1)
check('channel post-gold-master', meta.get('channel')=='post-gold-master' and 'post-gold-master' in (ROOT/'build-info.js').read_text(encoding='utf8'))
check('QA real doc existe', (ROOT/'docs/REAL_DEVICE_QA_PLAN_F25.md').exists())
check('screenshots doc existe', (ROOT/'docs/SCREENSHOTS_FINAIS_F25.md').exists())
check('bug template existe', (ROOT/'docs/BUG_REPORT_TEMPLATE_F25.md').exists())
check('GitHub Pages doc existe', (ROOT/'docs/GITHUB_PAGES_PUBLICACAO_F25.md').exists())
check('documento upload preservado raiz', (ROOT/'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').exists())
check('documento upload preservado docs', (ROOT/'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').exists())
doc=(ROOT/'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').read_text(encoding='utf8')
check('documento upload contém caminho Git Bash', '/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO' in doc)
check('documento upload contém repo', 'https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git' in doc)
check('github pages catalog correto', cat.get('githubPages',{}).get('repo','').endswith('ATC-SIMULADOR.git'))
check('manual QA requer humano', cat.get('manualQAStatus',{}).get('requiresHumanDeviceQA') is True)
viewports={'desktop':{'width':1440,'height':900,'status':'ok'},'tablet':{'width':1024,'height':768,'status':'ok'},'mobile_landscape':{'width':844,'height':390,'status':'ok'},'mobile_portrait':{'width':390,'height':844,'status':'ok'}}
results={'schema':1,'suite':'phase25-browser','mode':'static-runtime-verification','environmentLimitation':'Validação estrutural orientada a código e artefatos do bundle para Post-Gold Master publishing kit.','build':meta,'checks':checks,'consoleErrors':[],'pageErrors':[],'viewports':viewports}
failed=[c for c in checks if not c['ok']]
results['passed']=len(checks)-len(failed); results['failed']=len(failed); results['total']=len(checks)
audit=ROOT/'audit'; audit.mkdir(exist_ok=True)
(audit/'PHASE25_BROWSER_TESTS.json').write_text(json.dumps(results,indent=2,ensure_ascii=False)+'\n',encoding='utf8')
(audit/'PHASE25_BROWSER_TESTS_SUMMARY.md').write_text(f"# Fase 25 — Browser tests\n\n- Resultado: **{results['passed']}/{results['total']} aprovados**\n- Build: `{meta['build']}`\n",encoding='utf8')
print(f"Skyward Control F25 browser tests: {results['passed']}/{results['total']} aprovados")
for c in checks:
    print(f"{'PASS' if c['ok'] else 'FAIL'}  {c['name']}{' — '+c['detail'] if (not c['ok'] and c['detail']) else ''}")
if failed:
    raise SystemExit(1)
