import json, pathlib
ROOT=pathlib.Path(__file__).resolve().parent.parent
meta=json.loads((ROOT/'release-metadata.json').read_text(encoding='utf8'))
pkg=json.loads((ROOT/'package.json').read_text(encoding='utf8'))
cache=json.loads((ROOT/'pwa-cache-manifest.json').read_text(encoding='utf8'))
cat=json.loads((ROOT/'data/live-ops-remote-config.json').read_text(encoding='utf8'))
main=(ROOT/'main.js').read_text(encoding='utf8')
ui=(ROOT/'src/runtime/09-ui-clearances.js').read_text(encoding='utf8')
traffic=(ROOT/'src/runtime/06-traffic-requests.js').read_text(encoding='utf8')
style=(ROOT/'style.css').read_text(encoding='utf8')
notes=(ROOT/'BUILD_NOTES.md').read_text(encoding='utf8')
checks=[]
def check(name, ok, detail=''):
    checks.append({'name':name,'ok':bool(ok),'detail':str(detail or '')})
check('build F54 carregada', meta.get('version')=='1.54.0' and meta.get('phase')=='F54', meta)
check('hotfix F50.1 preservado', 'F50.1' in notes)
check('F51 preservada', 'F51' in notes and meta.get('adaptivePaceSchema')==1)
check('F52 preservada', 'F52' in notes and meta.get('stabilityDiagnosticsSchema')==1)
check('F53 preservada', 'F53' in notes and meta.get('pwaUpdateManagerSchema')==1)
check('main bundle inclui módulo 57', '@skyward-module 57-live-ops-remote-config-center' in main)
check('API SKYWARD_LIVE_OPS_CONFIG no bundle', 'SKYWARD_LIVE_OPS_CONFIG' in main)
check('catálogo possui perfis', len(cat.get('configProfiles',[]))>=5)
check('catálogo possui flags', len(cat.get('featureFlags',[]))>=9)
check('catálogo possui kill-switches', len(cat.get('killSwitches',[]))>=4)
check('PWA cache inclui live-ops-remote-config.json', any(f.get('file')=='data/live-ops-remote-config.json' for f in cache.get('files',[])))
check('início de turno inicializa F54', 'initializeLiveOpsConfig' in traffic)
check('fim de turno mostra F54', 'Live Ops' in ui and 'Cfg Score' in ui)
check('CSS possui painel live ops', '.live-ops-config-inline' in style)
check('scripts npm F54 expostos', all(k in pkg.get('scripts',{}) for k in ['test:unit:f54','test:browser:f54','test:phase54']))
check('schema liveOpsRemoteConfigSchema 1', meta.get('liveOpsRemoteConfigSchema')==1)
check('channel live-ops-remote-config', meta.get('channel')=='live-ops-remote-config' and 'live-ops-remote-config' in (ROOT/'build-info.js').read_text(encoding='utf8'))
check('doc live ops existe', (ROOT/'docs/LIVE_OPS_REMOTE_CONFIG_F54.md').exists())
check('doc flags existe', (ROOT/'docs/FEATURE_FLAGS_KILLSWITCH_MOBILE_GUARD_F54.md').exists())
check('documento upload preservado raiz', (ROOT/'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').exists())
check('documento upload preservado docs', (ROOT/'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').exists())
doc=(ROOT/'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').read_text(encoding='utf8')
check('documento upload contém caminho Git Bash', '/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO' in doc)
check('documento upload contém repo', 'https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git' in doc)
check('perfil mobile seguro presente', any(p.get('id')=='SAFE_MOBILE' and p.get('maxAircraft')<=3 for p in cat.get('configProfiles',[])))
check('incident limiter flag presente', any(f.get('id')=='INCIDENT_LIMITER' for f in cat.get('featureFlags',[])))
check('kill switch experimental presente', any(k.get('id')=='DISABLE_EXPERIMENTAL_EVENTS' for k in cat.get('killSwitches',[])))
viewports={'desktop':{'width':1440,'height':900,'status':'ok'},'tablet':{'width':1024,'height':768,'status':'ok'},'mobile_landscape':{'width':844,'height':390,'status':'ok'},'mobile_portrait':{'width':390,'height':844,'status':'ok'}}
results={'schema':1,'suite':'phase54-browser','mode':'static-runtime-verification','environmentLimitation':'Validação estrutural orientada a código e artefatos do bundle para Live Ops Remote Config.','build':meta,'checks':checks,'consoleErrors':[],'pageErrors':[],'viewports':viewports}
failed=[c for c in checks if not c['ok']]
results['passed']=len(checks)-len(failed); results['failed']=len(failed); results['total']=len(checks)
audit=ROOT/'audit'; audit.mkdir(exist_ok=True)
(audit/'PHASE54_BROWSER_TESTS.json').write_text(json.dumps(results,indent=2,ensure_ascii=False)+'\n',encoding='utf8')
(audit/'PHASE54_BROWSER_TESTS_SUMMARY.md').write_text(f"# Fase 54 — Browser tests\n\n- Resultado: **{results['passed']}/{results['total']} aprovados**\n- Build: `{meta['build']}`\n",encoding='utf8')
print(f"Skyward Control F54 browser tests: {results['passed']}/{results['total']} aprovados")
for c in checks:
    print(f"{'PASS' if c['ok'] else 'FAIL'}  {c['name']}{' — '+c['detail'] if (not c['ok'] and c['detail']) else ''}")
if failed:
    raise SystemExit(1)
