import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE29_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE29_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/training-coach-debriefing.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F29',metadata.version==='1.29.0'&&metadata.phase==='F29');check('build oficial F29',/^SC-1\.29\.0-F29-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('training coach schema 1',metadata.trainingCoachSchema===1&&config.trainingCoachSchema===1);check('canal training-coach',metadata.channel==='training-coach'&&config.channel==='training-coach');check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1&&metadata.releaseCandidateSchema===1&&metadata.goldMasterSchema===1&&metadata.postGoldMasterSchema===1&&metadata.postPublishHealthSchema===1&&metadata.publicOpsSchema===1&&metadata.trainingAcademySchema===1);}
if(order&&runtime){check('arquitetura geração 29',runtime.architectureGeneration===29);check('38 módulos oficiais',order.modules.length>=38&&runtime.moduleCount===order.modules.length);check('módulo coach antes de tráfego',order.modules.findIndex(m=>m.file==='32-training-coach-debriefing.js')>=0&&order.modules.findIndex(m=>m.file==='32-training-coach-debriefing.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F29 registrada',String(runtime.strategy).includes('training-coach-debriefing'));}
const source=read('src/runtime/32-training-coach-debriefing.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F29 integrado',source.includes('TRAINING_COACH_CATALOG')&&source.includes('window.SKYWARD_TRAINING_COACH=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.coachDomains?.length>=7&&catalog.studyCards?.length>=7&&catalog.adaptiveRules?.length>=7);
check('F29 conectado ao início',traffic.includes('initializeTrainingCoach'));
check('UI final mostra Instrutor',ui.includes('Instrutor ATC')&&ui.includes('Plano de estudo'));
check('CSS painel Coach',style.includes('.training-coach-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 32-training-coach-debriefing')&&bundle.includes('SKYWARD_TRAINING_COACH'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/training-coach-debriefing.json'));
check('docs F29 existem',fs.existsSync(path.join(root,'docs/INSTRUTOR_ATC_DEBRIEFING_F29.md'))&&fs.existsSync(path.join(root,'docs/PLANO_ESTUDO_ADAPTATIVO_F29.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
check('coach possui regras úteis',catalog.adaptiveRules.some(r=>r.id==='RULE_SLOT')&&catalog.studyCards.some(c=>c.id==='MISSED_APPROACH'));
const run=spawnSync(process.execPath,['tests/phase29-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F29 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=15,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F29 disponíveis',['test:unit:f29','test:browser:f29','test:phase29'].every(k=>pkg.scripts?.[k]));check('npm test contém F29',String(pkg.scripts.test).includes('test:unit:f29')&&String(pkg.scripts.test).includes('test:browser:f29')&&String(pkg.scripts.test).includes('test:phase29'));}
const required=['src/runtime/32-training-coach-debriefing.js','data/training-coach-debriefing.json','tests/phase29-unit-tests.mjs','tests/phase29-browser-tests.py','tests/phase29-audit.mjs','docs/INSTRUTOR_ATC_DEBRIEFING_F29.md','docs/PLANO_ESTUDO_ADAPTATIVO_F29.md','docs/FASE_29_CHECKLIST.md','docs/FASE_29_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE29_UNIT_TESTS.json','audit/PHASE29_BROWSER_TESTS.json'];check('artefatos F29 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F29 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
