import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE16_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE16_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/procedures-f16.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F16',metadata.version==='1.16.0'&&metadata.phase==='F16');check('build oficial F16',/^SC-1\.16\.0-F16-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('procedure ops schema 1',metadata.procedureOpsSchema===1&&config.procedureOpsSchema===1);check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1);}
if(order&&runtime){check('arquitetura geração 16',runtime.architectureGeneration===16);check('25 módulos oficiais',order.modules.length>=25&&runtime.moduleCount===order.modules.length);check('módulo procedimentos antes de tráfego',order.modules.findIndex(m=>m.file==='19-procedures-sid-star-rnav.js')>=0&&order.modules.findIndex(m=>m.file==='19-procedures-sid-star-rnav.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F16 registrada',String(runtime.strategy).includes('published-procedures'));}
const source=read('src/runtime/19-procedures-sid-star-rnav.js'),bundle=read('main.js'),sim=read('src/runtime/07-simulation-safety.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),render=read('src/runtime/08-radar-rendering.js');
check('módulo F16 integrado',source.includes('PUBLISHED_PROCEDURES_CATALOG')&&source.includes('window.SKYWARD_PROCEDURES=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&Object.keys(catalog.airports||{}).length>=3);
check('procedimentos essenciais presentes',['SBGR','SBSP','KATL'].every(a=>catalog.airports[a]?.stars?.length&&catalog.airports[a]?.sids?.length&&catalog.airports[a]?.approaches?.length&&catalog.airports[a]?.missedApproach&&catalog.airports[a]?.holds?.length));
check('tráfego inicializa procedimentos',traffic.includes('initializeProceduresLayer'));
check('simulação usa guidance',sim.includes('stepProcedureGuidance'));
check('UI usa procedimentos',ui.includes('assignArrivalProcedure')&&ui.includes('assignDepartureProcedure')&&ui.includes('assignMissedApproachProcedure'));
check('radar usa overlay',render.includes('drawPublishedProceduresOverlay'));
check('bundle sincronizado',bundle.includes('@skyward-module 19-procedures-sid-star-rnav')&&bundle.includes('SKYWARD_PROCEDURES'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/procedures-f16.json'));
check('documento upload presente',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
const run=spawnSync(process.execPath,['tests/phase16-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F16 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=16,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F16 disponíveis',['test:unit:f16','test:browser:f16','test:phase16'].every(k=>pkg.scripts?.[k]));check('npm test contém F16',String(pkg.scripts.test).includes('test:unit:f16')&&String(pkg.scripts.test).includes('test:browser:f16')&&String(pkg.scripts.test).includes('test:phase16'));}
const required=['src/runtime/19-procedures-sid-star-rnav.js','data/procedures-f16.json','tests/phase16-unit-tests.mjs','tests/phase16-browser-tests.py','tests/phase16-audit.mjs','docs/PROCEDIMENTOS_SID_STAR_ILS_RNAV_F16.md','docs/FASE_16_CHECKLIST.md','docs/FASE_16_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE16_UNIT_TESTS.json','audit/PHASE16_BROWSER_TESTS.json'];check('artefatos F16 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F16 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
