import json, pathlib
ROOT=pathlib.Path(__file__).resolve().parent.parent
meta=json.loads((ROOT/'release-metadata.json').read_text(encoding='utf8'))
pkg=json.loads((ROOT/'package.json').read_text(encoding='utf8'))
cache=json.loads((ROOT/'pwa-cache-manifest.json').read_text(encoding='utf8'))
cat=json.loads((ROOT/'data/scenario-mission-generator.json').read_text(encoding='utf8'))
main=(ROOT/'main.js').read_text(encoding='utf8')
ui=(ROOT/'src/runtime/09-ui-clearances.js').read_text(encoding='utf8')
traffic=(ROOT/'src/runtime/06-traffic-requests.js').read_text(encoding='utf8')
style=(ROOT/'style.css').read_text(encoding='utf8')
notes=(ROOT/'BUILD_NOTES.md').read_text(encoding='utf8')
checks=[]
def check(name, ok, detail=''):
    checks.append({'name':name,'ok':bool(ok),'detail':str(detail or '')})
check('build F55 carregada', meta.get('version')=='1.55.0' and meta.get('phase')=='F55', meta)
check('hotfix F50.1 preservado', 'F50.1' in notes)
check('F51 preservada', 'F51' in notes and meta.get('adaptivePaceSchema')==1)
check('F52 preservada', 'F52' in notes and meta.get('stabilityDiagnosticsSchema')==1)
check('F53 preservada', 'F53' in notes and meta.get('pwaUpdateManagerSchema')==1)
check('F54 preservada', 'F54' in notes and meta.get('liveOpsRemoteConfigSchema')==1)
check('main bundle inclui módulo 58', '@skyward-module 58-scenario-mission-generator-center' in main)
check('API SKYWARD_SCENARIO_MISSION no bundle', 'SKYWARD_SCENARIO_MISSION' in main)
check('catálogo possui templates', len(cat.get('missionTemplates',[]))>=7)
check('catálogo possui eventos', len(cat.get('eventTypes',[]))>=8)
check('catálogo possui objetivos', len(cat.get('objectiveTypes',[]))>=6)
check('PWA cache inclui scenario-mission-generator.json', any(f.get('file')=='data/scenario-mission-generator.json' for f in cache.get('files',[])))
check('início de turno inicializa F55', 'initializeScenarioMission' in traffic)
check('fim de turno mostra F55', 'Mission' in ui and 'Mission Score' in ui)
check('CSS possui painel scenario mission', '.scenario-mission-inline' in style)
check('scripts npm F55 expostos', all(k in pkg.get('scripts',{}) for k in ['test:unit:f55','test:browser:f55','test:phase55']))
check('schema scenarioMissionSchema 1', meta.get('scenarioMissionSchema')==1)
check('channel scenario-mission-generator', meta.get('channel')=='scenario-mission-generator' and 'scenario-mission-generator' in (ROOT/'build-info.js').read_text(encoding='utf8'))
check('doc scenario existe', (ROOT/'docs/SCENARIO_MISSION_GENERATOR_F55.md').exists())
check('doc objectives existe', (ROOT/'docs/MISSION_OBJECTIVES_EVENTS_REPLAY_F55.md').exists())
check('documento upload preservado raiz', (ROOT/'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').exists())
check('documento upload preservado docs', (ROOT/'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').exists())
doc=(ROOT/'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').read_text(encoding='utf8')
check('documento upload contém caminho Git Bash', '/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO' in doc)
check('documento upload contém repo', 'https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git' in doc)
check('mobile training template presente', any(t.get('id')=='MOBILE_TRAINING' for t in cat.get('missionTemplates',[])))
check('storm mission template presente', any(t.get('id')=='STORM_DIVERSION' for t in cat.get('missionTemplates',[])))
check('grade S presente', any(g.get('id')=='S' for g in cat.get('gradeBands',[])))
viewports={'desktop':{'width':1440,'height':900,'status':'ok'},'tablet':{'width':1024,'height':768,'status':'ok'},'mobile_landscape':{'width':844,'height':390,'status':'ok'},'mobile_portrait':{'width':390,'height':844,'status':'ok'}}
results={'schema':1,'suite':'phase55-browser','mode':'static-runtime-verification','environmentLimitation':'Validação estrutural orientada a código e artefatos do bundle para Scenario Mission Generator.','build':meta,'checks':checks,'consoleErrors':[],'pageErrors':[],'viewports':viewports}
failed=[c for c in checks if not c['ok']]
results['passed']=len(checks)-len(failed); results['failed']=len(failed); results['total']=len(checks)
audit=ROOT/'audit'; audit.mkdir(exist_ok=True)
(audit/'PHASE55_BROWSER_TESTS.json').write_text(json.dumps(results,indent=2,ensure_ascii=False)+'\n',encoding='utf8')
(audit/'PHASE55_BROWSER_TESTS_SUMMARY.md').write_text(f"# Fase 55 — Browser tests\n\n- Resultado: **{results['passed']}/{results['total']} aprovados**\n- Build: `{meta['build']}`\n",encoding='utf8')
print(f"Skyward Control F55 browser tests: {results['passed']}/{results['total']} aprovados")
for c in checks:
    print(f"{'PASS' if c['ok'] else 'FAIL'}  {c['name']}{' — '+c['detail'] if (not c['ok'] and c['detail']) else ''}")
if failed:
    raise SystemExit(1)
