import json, pathlib
ROOT=pathlib.Path(__file__).resolve().parent.parent
meta=json.loads((ROOT/'release-metadata.json').read_text(encoding='utf8'))
pkg=json.loads((ROOT/'package.json').read_text(encoding='utf8'))
cache=json.loads((ROOT/'pwa-cache-manifest.json').read_text(encoding='utf8'))
cat=json.loads((ROOT/'data/world-airport-procedures.json').read_text(encoding='utf8'))
main=(ROOT/'main.js').read_text(encoding='utf8')
ui=(ROOT/'src/runtime/09-ui-clearances.js').read_text(encoding='utf8')
traffic=(ROOT/'src/runtime/06-traffic-requests.js').read_text(encoding='utf8')
style=(ROOT/'style.css').read_text(encoding='utf8')
notes=(ROOT/'BUILD_NOTES.md').read_text(encoding='utf8')
checks=[]
def check(name, ok, detail=''):
    checks.append({'name':name,'ok':bool(ok),'detail':str(detail or '')})
check('build F59 carregada', meta.get('version')=='1.59.0' and meta.get('phase')=='F59', meta)
check('hotfix F50.1 preservado', 'F50.1' in notes)
check('F51 preservada', 'F51' in notes and meta.get('adaptivePaceSchema')==1)
check('F52 preservada', 'F52' in notes and meta.get('stabilityDiagnosticsSchema')==1)
check('F53 preservada', 'F53' in notes and meta.get('pwaUpdateManagerSchema')==1)
check('F54 preservada', 'F54' in notes and meta.get('liveOpsRemoteConfigSchema')==1)
check('F55 preservada', 'F55' in notes and meta.get('scenarioMissionSchema')==1)
check('F56 preservada', 'F56' in notes and meta.get('campaignProgressionSchema')==1)
check('F57 preservada', 'F57' in notes and meta.get('instructorDebriefSchema')==1)
check('F58 preservada', 'F58' in notes and meta.get('replayTimelineSchema')==1)
check('main bundle inclui módulo 62', '@skyward-module 62-world-airports-procedure-pack-center' in main)
check('API SKYWARD_WORLD_AIRPORTS no bundle', 'SKYWARD_WORLD_AIRPORTS' in main)
check('catálogo possui aeroportos', len(cat.get('airportPacks',[]))>=8)
check('catálogo possui procedimentos', len(cat.get('procedurePacks',[]))>=7)
check('catálogo possui rotas', len(cat.get('routeChallenges',[]))>=7)
check('PWA cache inclui world-airport-procedures.json', any(f.get('file')=='data/world-airport-procedures.json' for f in cache.get('files',[])))
check('início de turno inicializa F59', 'initializeWorldAirports' in traffic)
check('fim de turno mostra F59', 'Airport' in ui and 'Airport Score' in ui)
check('CSS possui painel world airport', '.world-airport-inline' in style)
check('scripts npm F59 expostos', all(k in pkg.get('scripts',{}) for k in ['test:unit:f59','test:browser:f59','test:phase59']))
check('schema worldAirportProcedureSchema 1', meta.get('worldAirportProcedureSchema')==1)
check('channel world-airports-procedures', meta.get('channel')=='world-airports-procedures' and 'world-airports-procedures' in (ROOT/'build-info.js').read_text(encoding='utf8'))
check('doc world airports existe', (ROOT/'docs/WORLD_AIRPORTS_PROCEDURES_F59.md').exists())
check('doc route challenges existe', (ROOT/'docs/AIRPORT_PACKS_ROUTE_CHALLENGES_F59.md').exists())
check('documento upload preservado raiz', (ROOT/'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').exists())
check('documento upload preservado docs', (ROOT/'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').exists())
doc=(ROOT/'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').read_text(encoding='utf8')
check('documento upload contém caminho Git Bash', '/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO' in doc)
check('documento upload contém repo', 'https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git' in doc)
check('SBSP presente', any(a.get('icao')=='SBSP' for a in cat.get('airportPacks',[])))
check('KJFK presente', any(a.get('icao')=='KJFK' for a in cat.get('airportPacks',[])))
check('parallel runway presente', any(p.get('id')=='PARALLEL_RUNWAY' for p in cat.get('procedurePacks',[])))
viewports={'desktop':{'width':1440,'height':900,'status':'ok'},'tablet':{'width':1024,'height':768,'status':'ok'},'mobile_landscape':{'width':844,'height':390,'status':'ok'},'mobile_portrait':{'width':390,'height':844,'status':'ok'}}
results={'schema':1,'suite':'phase59-browser','mode':'static-runtime-verification','environmentLimitation':'Validação estrutural orientada a código e artefatos do bundle para World Airports Procedure Packs.','build':meta,'checks':checks,'consoleErrors':[],'pageErrors':[],'viewports':viewports}
failed=[c for c in checks if not c['ok']]
results['passed']=len(checks)-len(failed); results['failed']=len(failed); results['total']=len(checks)
audit=ROOT/'audit'; audit.mkdir(exist_ok=True)
(audit/'PHASE59_BROWSER_TESTS.json').write_text(json.dumps(results,indent=2,ensure_ascii=False)+'\n',encoding='utf8')
(audit/'PHASE59_BROWSER_TESTS_SUMMARY.md').write_text(f"# Fase 59 — Browser tests\n\n- Resultado: **{results['passed']}/{results['total']} aprovados**\n- Build: `{meta['build']}`\n",encoding='utf8')
print(f"Skyward Control F59 browser tests: {results['passed']}/{results['total']} aprovados")
for c in checks:
    print(f"{'PASS' if c['ok'] else 'FAIL'}  {c['name']}{' — '+c['detail'] if (not c['ok'] and c['detail']) else ''}")
if failed:
    raise SystemExit(1)
