import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE15_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE15_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/weather-profiles.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F15',metadata.version==='1.15.0'&&metadata.phase==='F15');check('build oficial F15',/^SC-1\.15\.0-F15-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('weather ops schema 1',metadata.weatherOpsSchema===1&&config.weatherOpsSchema===1);check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1);}
if(order&&runtime){check('arquitetura geração 15',runtime.architectureGeneration===15);check('23 módulos oficiais',order.modules.length>=23&&runtime.moduleCount===order.modules.length);check('módulo weather antes de tráfego',order.modules.findIndex(m=>m.file==='18-advanced-weather-ifr.js')>=0&&order.modules.findIndex(m=>m.file==='18-advanced-weather-ifr.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F15 registrada',String(runtime.strategy).includes('advanced-ifr-vfr-weather'));}
const source=read('src/runtime/18-advanced-weather-ifr.js'),bundle=read('main.js'),sim=read('src/runtime/07-simulation-safety.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js');
check('módulo F15 integrado',source.includes('ADVANCED_WEATHER_CATALOG')&&source.includes('window.SKYWARD_WEATHER_OPS=Object.freeze'));
check('catálogo data-driven completo',catalog?.schema===1&&Object.keys(catalog.profiles||{}).length>=5);
check('perfis IFR/VFR/LIFR presentes',['VMC_CLEAR','IFR_LOW_CEILING','LIFR_RAIN','THUNDERSTORM_CELLS','FOG_RVR'].every(t=>JSON.stringify(catalog.profiles).includes(t)));
check('tráfego inicializa clima',traffic.includes('initializeAdvancedWeather'));
check('simulação usa risco de clima',sim.includes('advancedWeatherLandingRisk'));
check('commandRisk usa clima',ui.includes('weatherRiskForCommand'));
check('bundle sincronizado',bundle.includes('@skyward-module 18-advanced-weather-ifr')&&bundle.includes('SKYWARD_WEATHER_OPS'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/weather-profiles.json'));
const run=spawnSync(process.execPath,['tests/phase15-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F15 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=16,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=18,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F15 disponíveis',['test:unit:f15','test:browser:f15','test:phase15'].every(k=>pkg.scripts?.[k]));check('npm test contém F15',String(pkg.scripts.test).includes('test:unit:f15')&&String(pkg.scripts.test).includes('test:browser:f15')&&String(pkg.scripts.test).includes('test:phase15'));}
const release=read('tools/release.mjs');check('pipeline executa F15',release.includes('tests/phase15-unit-tests.mjs')&&release.includes('tests/phase15-browser-tests.py')&&release.includes('tests/phase15-audit.mjs'));
const required=['src/runtime/18-advanced-weather-ifr.js','data/weather-profiles.json','tests/phase15-unit-tests.mjs','tests/phase15-browser-tests.py','tests/phase15-audit.mjs','docs/METEOROLOGIA_AVANCADA_IFR_VFR_F15.md','docs/FASE_15_CHECKLIST.md','docs/FASE_15_AUDITORIA.md','audit/PHASE15_UNIT_TESTS.json','audit/PHASE15_BROWSER_TESTS.json'];check('artefatos F15 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F15 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
