import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE47_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE47_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/ground-turnaround.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F47',metadata.version==='1.47.0'&&metadata.phase==='F47');check('build oficial F47',/^SC-1\.47\.0-F47-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('ground turnaround schema 1',metadata.groundTurnaroundSchema===1&&config.groundTurnaroundSchema===1);check('canal ground-turnaround',metadata.channel==='ground-turnaround'&&config.channel==='ground-turnaround');check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1&&metadata.releaseCandidateSchema===1&&metadata.goldMasterSchema===1&&metadata.postGoldMasterSchema===1&&metadata.postPublishHealthSchema===1&&metadata.publicOpsSchema===1&&metadata.trainingAcademySchema===1&&metadata.trainingCoachSchema===1&&metadata.internationalCampaignSchema===1&&metadata.airlineOpsSchema===1&&metadata.airportAuthoritySchema===1&&metadata.crisisCommandSchema===1&&metadata.safetyComplianceSchema===1&&metadata.infrastructureExpansionSchema===1&&metadata.environmentSustainabilitySchema===1&&metadata.revenueManagementSchema===1&&metadata.workforceStaffingSchema===1&&metadata.passengerReputationSchema===1&&metadata.multiAirportNetworkSchema===1&&metadata.emergencyResponseSchema===1&&metadata.securityCyberDefenseSchema===1&&metadata.assetMaintenanceSchema===1&&metadata.digitalTwinPredictiveSchema===1&&metadata.aiCopilotSchema===1&&metadata.radioPhraseologySchema===1);}
if(order&&runtime){check('arquitetura geração 47',runtime.architectureGeneration===47);check('56 módulos oficiais',order.modules.length>=56&&runtime.moduleCount===order.modules.length);check('módulo ground antes de tráfego',order.modules.findIndex(m=>m.file==='50-ground-handling-turnaround-center.js')>=0&&order.modules.findIndex(m=>m.file==='50-ground-handling-turnaround-center.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F47 registrada',String(runtime.strategy).includes('ground-handling-turnaround-center'));}
const source=read('src/runtime/50-ground-handling-turnaround-center.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F47 integrado',source.includes('GROUND_TURNAROUND_CATALOG')&&source.includes('window.SKYWARD_GROUND_TURNAROUND=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.turnaroundProcesses?.length>=8&&catalog.delayCauses?.length>=7&&catalog.improvementPrograms?.length>=7);
check('F47 conectado ao início',traffic.includes('initializeGroundTurnaround'));
check('UI final mostra Ground Ops',ui.includes('Ground Ops')&&ui.includes('TAT Médio'));
check('CSS painel Ground',style.includes('.ground-turnaround-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 50-ground-handling-turnaround-center')&&bundle.includes('SKYWARD_GROUND_TURNAROUND'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/ground-turnaround.json'));
check('docs F47 existem',fs.existsSync(path.join(root,'docs/GROUND_TURNAROUND_F47.md'))&&fs.existsSync(path.join(root,'docs/GATE_PUSHBACK_BAGAGEM_COMBUSTIVEL_F47.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
check('ground possui pushback/fueling',catalog.turnaroundProcesses.some(p=>p.id==='PUSHBACK')&&catalog.turnaroundProcesses.some(p=>p.id==='FUELING'));
const run=spawnSync(process.execPath,['tests/phase47-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F47 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=12,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=22,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F47 disponíveis',['test:unit:f47','test:browser:f47','test:phase47'].every(k=>pkg.scripts?.[k]));check('npm test contém F47',String(pkg.scripts.test).includes('test:unit:f47')&&String(pkg.scripts.test).includes('test:browser:f47')&&String(pkg.scripts.test).includes('test:phase47'));}
const required=['src/runtime/50-ground-handling-turnaround-center.js','data/ground-turnaround.json','tests/phase47-unit-tests.mjs','tests/phase47-browser-tests.py','tests/phase47-audit.mjs','docs/GROUND_TURNAROUND_F47.md','docs/GATE_PUSHBACK_BAGAGEM_COMBUSTIVEL_F47.md','docs/FASE_47_CHECKLIST.md','docs/FASE_47_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE47_UNIT_TESTS.json','audit/PHASE47_BROWSER_TESTS.json'];check('artefatos F47 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F47 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
