import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE43_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE43_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/asset-maintenance-reliability.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F43',metadata.version==='1.43.0'&&metadata.phase==='F43');check('build oficial F43',/^SC-1\.43\.0-F43-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('asset maintenance schema 1',metadata.assetMaintenanceSchema===1&&config.assetMaintenanceSchema===1);check('canal asset-maintenance',metadata.channel==='asset-maintenance'&&config.channel==='asset-maintenance');check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1&&metadata.releaseCandidateSchema===1&&metadata.goldMasterSchema===1&&metadata.postGoldMasterSchema===1&&metadata.postPublishHealthSchema===1&&metadata.publicOpsSchema===1&&metadata.trainingAcademySchema===1&&metadata.trainingCoachSchema===1&&metadata.internationalCampaignSchema===1&&metadata.airlineOpsSchema===1&&metadata.airportAuthoritySchema===1&&metadata.crisisCommandSchema===1&&metadata.safetyComplianceSchema===1&&metadata.infrastructureExpansionSchema===1&&metadata.environmentSustainabilitySchema===1&&metadata.revenueManagementSchema===1&&metadata.workforceStaffingSchema===1&&metadata.passengerReputationSchema===1&&metadata.multiAirportNetworkSchema===1&&metadata.emergencyResponseSchema===1&&metadata.securityCyberDefenseSchema===1);}
if(order&&runtime){check('arquitetura geração 43',runtime.architectureGeneration===43);check('52 módulos oficiais',order.modules.length>=52&&runtime.moduleCount===order.modules.length);check('módulo asset antes de tráfego',order.modules.findIndex(m=>m.file==='46-asset-maintenance-reliability-center.js')>=0&&order.modules.findIndex(m=>m.file==='46-asset-maintenance-reliability-center.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F43 registrada',String(runtime.strategy).includes('asset-maintenance-reliability-center'));}
const source=read('src/runtime/46-asset-maintenance-reliability-center.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F43 integrado',source.includes('ASSET_MAINTENANCE_CATALOG')&&source.includes('window.SKYWARD_ASSET_MAINTENANCE=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.assetClasses?.length>=8&&catalog.failureModes?.length>=8&&catalog.maintenancePrograms?.length>=7);
check('F43 conectado ao início',traffic.includes('initializeAssetMaintenance'));
check('UI final mostra Asset Rel',ui.includes('Asset Rel')&&ui.includes('Disponib.'));
check('CSS painel Asset',style.includes('.asset-maintenance-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 46-asset-maintenance-reliability-center')&&bundle.includes('SKYWARD_ASSET_MAINTENANCE'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/asset-maintenance-reliability.json'));
check('docs F43 existem',fs.existsSync(path.join(root,'docs/ASSET_MAINTENANCE_RELIABILITY_F43.md'))&&fs.existsSync(path.join(root,'docs/RADAR_ILS_BALIZAMENTO_MTTR_F43.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
check('asset possui radar/ILS',catalog.assetClasses.some(a=>a.id==='PRIMARY_RADAR')&&catalog.assetClasses.some(a=>a.id==='ILS_CAT'));
const run=spawnSync(process.execPath,['tests/phase43-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F43 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=15,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F43 disponíveis',['test:unit:f43','test:browser:f43','test:phase43'].every(k=>pkg.scripts?.[k]));check('npm test contém F43',String(pkg.scripts.test).includes('test:unit:f43')&&String(pkg.scripts.test).includes('test:browser:f43')&&String(pkg.scripts.test).includes('test:phase43'));}
const required=['src/runtime/46-asset-maintenance-reliability-center.js','data/asset-maintenance-reliability.json','tests/phase43-unit-tests.mjs','tests/phase43-browser-tests.py','tests/phase43-audit.mjs','docs/ASSET_MAINTENANCE_RELIABILITY_F43.md','docs/RADAR_ILS_BALIZAMENTO_MTTR_F43.md','docs/FASE_43_CHECKLIST.md','docs/FASE_43_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE43_UNIT_TESTS.json','audit/PHASE43_BROWSER_TESTS.json'];check('artefatos F43 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F43 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
