import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE18_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE18_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/economy-contracts.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F18',metadata.version==='1.18.0'&&metadata.phase==='F18');check('build oficial F18',/^SC-1\.18\.0-F18-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('economy schema 1',metadata.economySchema===1&&config.economySchema===1);check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1);}
if(order&&runtime){check('arquitetura geração 18',runtime.architectureGeneration===18);check('27 módulos oficiais',order.modules.length>=27&&runtime.moduleCount===order.modules.length);check('módulo economia antes de tráfego',order.modules.findIndex(m=>m.file==='21-operational-economy.js')>=0&&order.modules.findIndex(m=>m.file==='21-operational-economy.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F18 registrada',String(runtime.strategy).includes('airport-operational-economy'));}
const source=read('src/runtime/21-operational-economy.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F18 integrado',source.includes('SKYWARD_ECONOMY_CATALOG')&&source.includes('window.SKYWARD_ECONOMY=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&Object.keys(catalog.airportBudgets||{}).length>=5&&catalog.airlineContracts?.length>=5);
check('economia conectada ao início',traffic.includes('renderEconomyBoard'));
check('economia conectada ao final',ui.includes('evaluateOperationalEconomy'));
check('UI final mostra economia',ui.includes('Economia')&&ui.includes('Eficiência econômica'));
check('painel economia no CSS',style.includes('.economy-ops-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 21-operational-economy')&&bundle.includes('SKYWARD_ECONOMY'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/economy-contracts.json'));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
const run=spawnSync(process.execPath,['tests/phase18-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F18 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=16,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F18 disponíveis',['test:unit:f18','test:browser:f18','test:phase18'].every(k=>pkg.scripts?.[k]));check('npm test contém F18',String(pkg.scripts.test).includes('test:unit:f18')&&String(pkg.scripts.test).includes('test:browser:f18')&&String(pkg.scripts.test).includes('test:phase18'));}
const required=['src/runtime/21-operational-economy.js','data/economy-contracts.json','tests/phase18-unit-tests.mjs','tests/phase18-browser-tests.py','tests/phase18-audit.mjs','docs/ECONOMIA_OPERACIONAL_F18.md','docs/FASE_18_CHECKLIST.md','docs/FASE_18_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE18_UNIT_TESTS.json','audit/PHASE18_BROWSER_TESTS.json'];check('artefatos F18 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F18 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
