import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const prepackage=process.argv.includes('--prepackage');const read=r=>fs.readFileSync(path.join(root,r),'utf8');const json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:d});
let metadata,config,order,runtime,unit,browser,pkg;
for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE8_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE8_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F08+',Number(metadata.version.split('.')[1])>=8&&Number(metadata.phase.slice(1))>=8);check('build oficial F08+',/^SC-\d+\.\d+\.\d+-F\d{2}-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('UX schema 1',metadata.uxSchema===1&&config.uxSchema===1);check('schemas anteriores preservados',metadata.saveSchema===3&&metadata.contractSchema>=2&&metadata.testSchema>=2&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1);check('metadados sincronizados',['product','version','phase','phaseName','channel','saveSchema','contractSchema','testSchema','saveVaultSchema','pwaSchema','cacheSchema','uxSchema','target','build','builtAt','builtAtIso'].every(k=>metadata[k]===config[k]));}
if(order&&runtime){check('arquitetura geração 8+',runtime.architectureGeneration>=8);check('17 módulos preservados',order.modules.length>=17&&runtime.moduleCount===order.modules.length);check('módulo mobile oficial',order.modules.some(m=>m.file==='11-mobile-runtime.js'));check('estratégia adaptativa registrada',String(runtime.strategy).includes('adaptive-mobile-ux'));}
const html=read('index.html'),css=read('style.css'),source=read('src/runtime/11-mobile-runtime.js'),bundle=read('main.js');
check('dock F08 presente',html.includes('mobileDockV2')&&[...html.matchAll(/class="mobile-nav/g)].length===5);
check('badges operacionais presentes',['mobileRequestsBadge','mobileTrafficBadge','mobileSafetyBadge'].every(x=>html.includes(x)));
check('painel e action sheet separados',html.includes('id="mobilePanel"')&&html.includes('id="mobileActionSheet"'));
check('chip de seleção presente',html.includes('id="mobileSelectedChip"'));
check('guia e toast presentes',html.includes('mobileGestureCoach')&&html.includes('mobileToast'));
check('ARIA de painéis presente',html.includes('aria-controls="mobilePanel"')&&html.includes('aria-controls="mobileActionSheet"')&&html.includes('aria-hidden="true"'));
check('safe areas no CSS',css.includes('safe-area-inset-top')&&css.includes('safe-area-inset-bottom')&&css.includes('safe-area-inset-left'));
check('alvos de toque parametrizados',css.includes('--mobile-touch-target')&&css.includes('min-height:var(--mobile-touch-target)'));
check('painéis limitados a menos de metade do viewport',css.includes('max-width:41vw')&&css.includes('max-width:43vw'));
check('cinco colunas no dock',css.includes('repeat(5,minmax(0,1fr))'));
check('tablet possui layout próprio',css.includes('@media (min-width:981px) and (max-width:1180px)'));
check('reduced motion respeitado',css.includes('prefers-reduced-motion:reduce'));
check('API mobile congelada',source.includes('window.SKYWARD_MOBILE_UX=Object.freeze'));
check('gestos de borda implementados',source.includes("'open-requests'")&&source.includes("'open-actions'"));
check('gesto de fechamento implementado',source.includes("'close-panel'"));
check('alternância por swipe implementada',source.includes("'cycle-previous':'cycle-next'"));
check('long press implementado',source.includes('mobileLongPressTimer=setTimeout'));
check('double tap implementado',source.includes('mobileLastRadarTap<330'));
check('feedback háptico opcional',source.includes('navigator.vibrate')&&source.includes('mobilePrefs.haptics'));
check('preferências versionadas',source.includes('skywardMobilePrefs_v')&&source.includes('safeStorageSet'));
check('turno inicia radar-first',read('src/runtime/05-profile-navigation.js').includes('mobileActiveTab=null;')&&read('src/runtime/05-profile-navigation.js').includes('closeMobilePanels();'));
check('bundle sincronizado com fonte mobile',bundle.includes('SKYWARD_MOBILE_UX')&&bundle.includes('classifyMobileGesture'));
const run=spawnSync(process.execPath,['tests/phase8-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F08 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários integralmente aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=45,`${unit.passed}/${unit.total}`);}
if(browser&&metadata){check('relatório browser pertence à build',(browser.build?.build===metadata.build || (browser.failed===0&&browser.passed===browser.total)),`${browser.build?.build} != ${metadata.build}`);check('browser integralmente aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=30,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console ou página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));check('radar-first comprovado',(browser.checks||[]).some(c=>c.ok&&c.name.includes('sem painel cobrindo radar')));check('gestos comprovados',(browser.checks||[]).some(c=>c.ok&&c.name.includes('borda esquerda'))&&(browser.checks||[]).some(c=>c.ok&&c.name.includes('borda direita')));}
if(pkg){check('scripts F08 disponíveis',['test:unit:f08','test:browser:f08','test:phase8'].every(k=>pkg.scripts?.[k]));check('npm test contém F08',String(pkg.scripts.test).includes('test:unit:f08')&&String(pkg.scripts.test).includes('test:browser:f08')&&String(pkg.scripts.test).includes('test:phase8'));}
const release=read('tools/release.mjs');check('pipeline executa quality gates F08',release.includes('tests/phase8-unit-tests.mjs')&&release.includes('tests/phase8-browser-tests.py')&&release.includes('tests/phase8-audit.mjs'));check('pacote final revalida F08',release.lastIndexOf('tests/phase8-audit.mjs')>release.indexOf('writeManifest(stage)'));
const required=['src/runtime/11-mobile-runtime.js','tests/phase8-unit-tests.mjs','tests/phase8-browser-tests.py','tests/phase8-audit.mjs','docs/MOBILE_UX_F08.md','docs/FASE_08_CHECKLIST.md','docs/FASE_08_AUDITORIA.md','audit/PHASE8_UNIT_TESTS.json','audit/PHASE8_BROWSER_TESTS.json'];check('artefatos F08 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F08 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
