import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:d});
let metadata,config,order,runtime,unit,browser,pkg;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE10_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE10_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F10+',/^F(1[0-9]|[2-9][0-9])$/.test(metadata.phase));check('build oficial F10+',/^SC-\d+\.\d+\.\d+-F\d{2}-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('accessibility schema 1',metadata.accessibilitySchema===1&&config.accessibilitySchema===1);check('schemas anteriores preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema>=2&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1);check('metadados sincronizados',['product','version','phase','phaseName','channel','saveSchema','contractSchema','testSchema','saveVaultSchema','pwaSchema','cacheSchema','uxSchema','desktopSchema','accessibilitySchema','replaySchema','target','build','builtAt','builtAtIso'].every(k=>metadata[k]===config[k]));}
if(order&&runtime){check('arquitetura geração 10',runtime.architectureGeneration>=10);check('19 módulos oficiais',order.modules.length>=19&&runtime.moduleCount===order.modules.length);check('módulo acessibilidade antes do bridge QA',order.modules.findIndex(m=>m.file==='13-accessibility-settings.js')>=0&&order.modules.findIndex(m=>m.file==='13-accessibility-settings.js')<order.modules.findIndex(m=>m.file==='12-quality-test-bridge.js'));check('estratégia F10 registrada',String(runtime.strategy).includes('professional-accessibility-settings'));}
const html=read('index.html'),css=read('style.css'),source=read('src/runtime/13-accessibility-settings.js'),bundle=read('main.js');
check('painel F10 integrado',html.includes('accessibilityPanel')&&html.includes('data-accessibility-schema="1"'));
check('gatilhos em menu jogo e mobile',html.includes('ACESSIBILIDADE / CONFIG')&&html.includes('accessibilityBadge')&&html.includes('mobileSettingsBtn'));
check('configurações visuais completas',['uiScale','contrast','colorMode','radarBrightness'].every(x=>html.includes(`data-access-setting="${x}"`)));
check('configurações de áudio completas',['masterVolume','radioVolume','sfxVolume','haptics'].every(x=>html.includes(`data-access-setting="${x}"`)));
check('configurações de desempenho completas',['performanceMode','fpsCap','effects','touchMode'].every(x=>html.includes(`data-access-setting="${x}"`)));
check('CSS escala/contraste/daltonismo',css.includes('--ui-scale')&&css.includes('data-contrast="high"')&&css.includes('data-color-mode="mono"'));
check('CSS acessibilidade mobile',css.includes('mobile-settings-btn')&&css.includes('@media (max-width:980px)'));
check('CSS reduz movimentos',css.includes('access-reduced-motion')&&css.includes('@media (prefers-reduced-motion:reduce)'));
check('API congelada',source.includes('window.SKYWARD_ACCESSIBILITY=Object.freeze'));
check('sanitização F10',source.includes('sanitizeAccessibilityPrefs')&&source.includes('accessClamp'));
check('persistência F10',source.includes('skywardAccessibilitySettings_v')&&source.includes('safeStorageSet'));
check('atalhos F10',source.includes('F10')&&source.includes('altKey&&e.code'));
check('bundle sincronizado',bundle.includes('@skyward-module 13-accessibility-settings')&&bundle.includes('SKYWARD_ACCESSIBILITY'));
const run=spawnSync(process.execPath,['tests/phase10-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F10 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=35,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',(browser.build?.build===metadata.build || (browser.failed===0&&browser.passed===browser.total)),`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=30,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));check('alto contraste comprovado',(browser.checks||[]).some(c=>c.ok&&c.name.includes('alto contraste')));check('mobile settings comprovado',(browser.checks||[]).some(c=>c.ok&&c.name.includes('mobile landscape: configurações')));}
if(pkg){check('scripts F10 disponíveis',['test:unit:f10','test:browser:f10','test:phase10'].every(k=>pkg.scripts?.[k]));check('npm test contém F10',String(pkg.scripts.test).includes('test:unit:f10')&&String(pkg.scripts.test).includes('test:browser:f10')&&String(pkg.scripts.test).includes('test:phase10'));}
const release=read('tools/release.mjs');check('pipeline executa F10',release.includes('tests/phase10-unit-tests.mjs')&&release.includes('tests/phase10-browser-tests.py')&&release.includes('tests/phase10-audit.mjs'));check('pacote revalida F10',release.lastIndexOf('tests/phase10-audit.mjs')>release.indexOf('writeManifest(stage)'));
const required=['src/runtime/13-accessibility-settings.js','tests/phase10-unit-tests.mjs','tests/phase10-browser-tests.py','tests/phase10-audit.mjs','docs/ACESSIBILIDADE_CONFIGURACOES_F10.md','docs/FASE_10_CHECKLIST.md','docs/FASE_10_AUDITORIA.md','audit/PHASE10_UNIT_TESTS.json','audit/PHASE10_BROWSER_TESTS.json'];check('artefatos F10 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F10 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
