import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE26_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE26_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/post-publish-healthcheck.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F26',metadata.version==='1.26.0'&&metadata.phase==='F26');check('build oficial F26',/^SC-1\.26\.0-F26-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('post publish health schema 1',metadata.postPublishHealthSchema===1&&config.postPublishHealthSchema===1);check('canal post-publish-healthcheck',metadata.channel==='post-publish-healthcheck'&&config.channel==='post-publish-healthcheck');check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1&&metadata.releaseCandidateSchema===1&&metadata.goldMasterSchema===1&&metadata.postGoldMasterSchema===1);}
if(order&&runtime){check('arquitetura geração 26',runtime.architectureGeneration===26);check('35 módulos oficiais',order.modules.length>=35&&runtime.moduleCount===order.modules.length);check('módulo health antes de tráfego',order.modules.findIndex(m=>m.file==='29-post-publish-healthcheck.js')>=0&&order.modules.findIndex(m=>m.file==='29-post-publish-healthcheck.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F26 registrada',String(runtime.strategy).includes('post-publish-healthcheck'));}
const source=read('src/runtime/29-post-publish-healthcheck.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F26 integrado',source.includes('POST_PUBLISH_CATALOG')&&source.includes('window.SKYWARD_POST_PUBLISH_HEALTH=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.healthChecks?.length>=10&&catalog.hotfixDeck?.length>=5&&catalog.promotionRules?.length>=3);
check('F26 conectado ao início',traffic.includes('initializePostPublishHealthcheck'));
check('UI final mostra health',ui.includes('Publish Health')&&ui.includes('Health Score'));
check('CSS painel health',style.includes('.post-publish-health-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 29-post-publish-healthcheck')&&bundle.includes('SKYWARD_POST_PUBLISH_HEALTH'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/post-publish-healthcheck.json'));
check('docs F26 existem',fs.existsSync(path.join(root,'docs/POST_PUBLISH_HEALTHCHECK_F26.md'))&&fs.existsSync(path.join(root,'docs/PUBLICATION_HEALTH_QA_F26.md'))&&fs.existsSync(path.join(root,'docs/HOTFIX_DECK_F26.md'))&&fs.existsSync(path.join(root,'docs/COMANDOS_UPLOAD_F26.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
check('GitHub Pages URL correta',catalog.publicVerification?.expectedUrl?.includes('github.io/ATC-SIMULADOR'));
const run=spawnSync(process.execPath,['tests/phase26-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F26 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=14,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F26 disponíveis',['test:unit:f26','test:browser:f26','test:phase26'].every(k=>pkg.scripts?.[k]));check('npm test contém F26',String(pkg.scripts.test).includes('test:unit:f26')&&String(pkg.scripts.test).includes('test:browser:f26')&&String(pkg.scripts.test).includes('test:phase26'));}
const required=['src/runtime/29-post-publish-healthcheck.js','data/post-publish-healthcheck.json','tests/phase26-unit-tests.mjs','tests/phase26-browser-tests.py','tests/phase26-audit.mjs','docs/POST_PUBLISH_HEALTHCHECK_F26.md','docs/PUBLICATION_HEALTH_QA_F26.md','docs/HOTFIX_DECK_F26.md','docs/COMANDOS_UPLOAD_F26.md','docs/FASE_26_CHECKLIST.md','docs/FASE_26_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE26_UNIT_TESTS.json','audit/PHASE26_BROWSER_TESTS.json'];check('artefatos F26 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F26 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
