import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,hotspots;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE14_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE14_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['hotspots','data/surface-hotspots.json',v=>hotspots=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F14',metadata.version==='1.14.0'&&metadata.phase==='F14');check('build oficial F14',/^SC-1\.14\.0-F14-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('surface safety schema 1',metadata.surfaceSafetySchema===1&&config.surfaceSafetySchema===1);check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1);check('metadados sincronizados',['product','version','phase','phaseName','channel','saveSchema','contractSchema','testSchema','saveVaultSchema','pwaSchema','cacheSchema','uxSchema','desktopSchema','accessibilitySchema','replaySchema','aircraftPerformanceSchema','airportSurfaceSchema','surfaceSafetySchema','target','build','builtAt','builtAtIso'].every(k=>metadata[k]===config[k]));}
if(order&&runtime){check('arquitetura geração 14',runtime.architectureGeneration===14);check('23 módulos oficiais',order.modules.length>=23&&runtime.moduleCount===order.modules.length);check('módulo surface safety antes da simulação',order.modules.findIndex(m=>m.file==='17-surface-safety-director.js')>=0&&order.modules.findIndex(m=>m.file==='17-surface-safety-director.js')<order.modules.findIndex(m=>m.file==='07-simulation-safety.js'));check('estratégia F14 registrada',String(runtime.strategy).includes('surface-safety-director'));}
const source=read('src/runtime/17-surface-safety-director.js'),bundle=read('main.js'),sim=read('src/runtime/07-simulation-safety.js'),ui=read('src/runtime/09-ui-clearances.js');
check('módulo F14 integrado',source.includes('SURFACE_HOTSPOTS')&&source.includes('window.SKYWARD_SURFACE_SAFETY=Object.freeze'));
check('hotspots data-driven completos',hotspots?.schema===1&&Object.keys(hotspots.airports||{}).length>=5);
check('aeroportos-chave com hotspots',['SBGR','SBSP','SBKP','SBBR','KATL'].every(t=>JSON.stringify(hotspots.airports).includes(t)));
check('detecção runway incursion',source.includes('detectRunwayIncursions')&&source.includes('Runway incursion'));
check('detecção taxi conflict',source.includes('detectTaxiConflicts')&&source.includes('Conflito de solo'));
check('comando usa surface safety',sim.includes('surfaceCommandRisk')&&sim.includes('updateSurfaceSafetyDirector'));
check('UI e estatísticas F14',ui.includes('SURFACE')&&ui.includes('surfaceConflicts')&&ui.includes('Runway incursions'));
check('bundle sincronizado',bundle.includes('@skyward-module 17-surface-safety-director')&&bundle.includes('SKYWARD_SURFACE_SAFETY'));
check('PWA cache inclui hotspots',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/surface-hotspots.json'));
const run=spawnSync(process.execPath,['tests/phase14-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F14 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=16,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=18,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));check('incursion comprovada',(browser.checks||[]).some(c=>c.ok&&c.name.includes('incursion')));}
if(pkg){check('scripts F14 disponíveis',['test:unit:f14','test:browser:f14','test:phase14'].every(k=>pkg.scripts?.[k]));check('npm test contém F14',String(pkg.scripts.test).includes('test:unit:f14')&&String(pkg.scripts.test).includes('test:browser:f14')&&String(pkg.scripts.test).includes('test:phase14'));}
const release=read('tools/release.mjs');check('pipeline executa F14',release.includes('tests/phase14-unit-tests.mjs')&&release.includes('tests/phase14-browser-tests.py')&&release.includes('tests/phase14-audit.mjs'));check('pacote revalida F14',release.lastIndexOf('tests/phase14-audit.mjs')>release.indexOf('writeManifest(stage)'));
const required=['src/runtime/17-surface-safety-director.js','data/surface-hotspots.json','tests/phase14-unit-tests.mjs','tests/phase14-browser-tests.py','tests/phase14-audit.mjs','docs/SURFACE_SAFETY_DIRECTOR_F14.md','docs/FASE_14_CHECKLIST.md','docs/FASE_14_AUDITORIA.md','audit/PHASE14_UNIT_TESTS.json','audit/PHASE14_BROWSER_TESTS.json'];check('artefatos F14 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F14 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
