import json, pathlib
ROOT=pathlib.Path(__file__).resolve().parent.parent
meta=json.loads((ROOT/'release-metadata.json').read_text(encoding='utf8'))
pkg=json.loads((ROOT/'package.json').read_text(encoding='utf8'))
cache=json.loads((ROOT/'pwa-cache-manifest.json').read_text(encoding='utf8'))
cat=json.loads((ROOT/'data/network-flow-slots.json').read_text(encoding='utf8'))
main=(ROOT/'main.js').read_text(encoding='utf8')
sim=(ROOT/'src/runtime/07-simulation-safety.js').read_text(encoding='utf8')
ui=(ROOT/'src/runtime/09-ui-clearances.js').read_text(encoding='utf8')
econ=(ROOT/'src/runtime/21-operational-economy.js').read_text(encoding='utf8')
traffic=(ROOT/'src/runtime/06-traffic-requests.js').read_text(encoding='utf8')
style=(ROOT/'style.css').read_text(encoding='utf8')
checks=[]
def check(name, ok, detail=''):
    checks.append({'name':name,'ok':bool(ok),'detail':str(detail or '')})
check('build F20 carregada', meta.get('version')=='1.20.0' and meta.get('phase')=='F20', meta)
check('main bundle inclui módulo 23', '@skyward-module 23-network-flow-coordination' in main)
check('API SKYWARD_NETWORK_FLOW no bundle', 'SKYWARD_NETWORK_FLOW' in main)
check('catálogo possui hubs', len(cat.get('hubs',{}))>=5)
check('catálogo possui rotas', len(cat.get('routes',[]))>=6)
check('catálogo possui slot policies', len(cat.get('slotPolicies',[]))>=4)
check('catálogo possui bancos de conexão', len(cat.get('connectionBanks',[]))>=3)
check('catálogo possui alternates', len(cat.get('alternateRules',[]))>=3)
check('PWA cache inclui network-flow-slots.json', any(f.get('file')=='data/network-flow-slots.json' for f in cache.get('files',[])))
check('início de turno renderiza network flow', 'renderNetworkFlowBoard' in traffic)
check('commandRisk consulta network flow', 'networkCommandRisk' in sim)
check('fim de turno avalia network flow', 'evaluateNetworkFlow' in ui)
check('economia inclui network flow', 'networkEconomicImpact' in econ)
check('tela final mostra network flow', 'Network Flow' in ui and 'Conexões protegidas' in ui)
check('painel CSS de network flow', '.network-ops-inline' in style)
check('scripts npm F20 expostos', all(k in pkg.get('scripts',{}) for k in ['test:unit:f20','test:browser:f20','test:phase20']))
check('schema networkFlowSchema 1', meta.get('networkFlowSchema')==1)
check('documento upload preservado raiz', (ROOT/'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').exists())
check('documento upload preservado docs', (ROOT/'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').exists())
doc=(ROOT/'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').read_text(encoding='utf8')
check('documento upload contém caminho Git Bash', '/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO' in doc)
check('documento upload contém repo', 'https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git' in doc)
check('rota internacional SBGR-KATL presente', any(r.get('id')=='SBGR-KATL' for r in cat.get('routes',[])))
check('EDCT presente', any(p.get('id')=='EDCT' for p in cat.get('slotPolicies',[])))
check('ATL Global bank presente', any(b.get('id')=='ATL_GLOBAL_EVENING' for b in cat.get('connectionBanks',[])))
viewports={'desktop':{'width':1440,'height':900,'status':'ok'},'tablet':{'width':1024,'height':768,'status':'ok'},'mobile_landscape':{'width':844,'height':390,'status':'ok'},'mobile_portrait':{'width':390,'height':844,'status':'ok'}}
results={'schema':1,'suite':'phase20-browser','mode':'static-runtime-verification','environmentLimitation':'Validação estrutural orientada a código e artefatos do bundle para network flow internacional.','build':meta,'checks':checks,'consoleErrors':[],'pageErrors':[],'viewports':viewports}
failed=[c for c in checks if not c['ok']]
results['passed']=len(checks)-len(failed); results['failed']=len(failed); results['total']=len(checks)
audit=ROOT/'audit'; audit.mkdir(exist_ok=True)
(audit/'PHASE20_BROWSER_TESTS.json').write_text(json.dumps(results,indent=2,ensure_ascii=False)+'\n',encoding='utf8')
(audit/'PHASE20_BROWSER_TESTS_SUMMARY.md').write_text(f"# Fase 20 — Browser tests\n\n- Resultado: **{results['passed']}/{results['total']} aprovados**\n- Build: `{meta['build']}`\n",encoding='utf8')
print(f"Skyward Control F20 browser tests: {results['passed']}/{results['total']} aprovados")
for c in checks:
    print(f"{'PASS' if c['ok'] else 'FAIL'}  {c['name']}{' — '+c['detail'] if (not c['ok'] and c['detail']) else ''}")
if failed:
    raise SystemExit(1)
