import json, pathlib
ROOT=pathlib.Path(__file__).resolve().parent.parent
meta=json.loads((ROOT/'release-metadata.json').read_text(encoding='utf8'))
pkg=json.loads((ROOT/'package.json').read_text(encoding='utf8'))
cache=json.loads((ROOT/'pwa-cache-manifest.json').read_text(encoding='utf8'))
cat=json.loads((ROOT/'data/instructor-debrief.json').read_text(encoding='utf8'))
main=(ROOT/'main.js').read_text(encoding='utf8')
ui=(ROOT/'src/runtime/09-ui-clearances.js').read_text(encoding='utf8')
traffic=(ROOT/'src/runtime/06-traffic-requests.js').read_text(encoding='utf8')
style=(ROOT/'style.css').read_text(encoding='utf8')
notes=(ROOT/'BUILD_NOTES.md').read_text(encoding='utf8')
checks=[]
def check(name, ok, detail=''):
    checks.append({'name':name,'ok':bool(ok),'detail':str(detail or '')})
check('build F57 carregada', meta.get('version')=='1.57.0' and meta.get('phase')=='F57', meta)
check('hotfix F50.1 preservado', 'F50.1' in notes)
check('F51 preservada', 'F51' in notes and meta.get('adaptivePaceSchema')==1)
check('F52 preservada', 'F52' in notes and meta.get('stabilityDiagnosticsSchema')==1)
check('F53 preservada', 'F53' in notes and meta.get('pwaUpdateManagerSchema')==1)
check('F54 preservada', 'F54' in notes and meta.get('liveOpsRemoteConfigSchema')==1)
check('F55 preservada', 'F55' in notes and meta.get('scenarioMissionSchema')==1)
check('F56 preservada', 'F56' in notes and meta.get('campaignProgressionSchema')==1)
check('main bundle inclui módulo 60', '@skyward-module 60-instructor-debrief-replay-analytics-center' in main)
check('API SKYWARD_INSTRUCTOR_DEBRIEF no bundle', 'SKYWARD_INSTRUCTOR_DEBRIEF' in main)
check('catálogo possui áreas', len(cat.get('reviewAreas',[]))>=8)
check('catálogo possui erros', len(cat.get('errorTaxonomy',[]))>=8)
check('catálogo possui drills', len(cat.get('trainingDrills',[]))>=7)
check('PWA cache inclui instructor-debrief.json', any(f.get('file')=='data/instructor-debrief.json' for f in cache.get('files',[])))
check('início de turno inicializa F57', 'initializeInstructorDebrief' in traffic)
check('fim de turno mostra F57', 'Debrief' in ui and 'Treino' in ui)
check('CSS possui painel instructor debrief', '.instructor-debrief-inline' in style)
check('scripts npm F57 expostos', all(k in pkg.get('scripts',{}) for k in ['test:unit:f57','test:browser:f57','test:phase57']))
check('schema instructorDebriefSchema 1', meta.get('instructorDebriefSchema')==1)
check('channel instructor-debrief', meta.get('channel')=='instructor-debrief' and 'instructor-debrief' in (ROOT/'build-info.js').read_text(encoding='utf8'))
check('doc debrief existe', (ROOT/'docs/INSTRUCTOR_DEBRIEF_F57.md').exists())
check('doc replay analytics existe', (ROOT/'docs/REPLAY_ANALYTICS_TRAINING_FEEDBACK_F57.md').exists())
check('documento upload preservado raiz', (ROOT/'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').exists())
check('documento upload preservado docs', (ROOT/'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').exists())
doc=(ROOT/'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').read_text(encoding='utf8')
check('documento upload contém caminho Git Bash', '/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO' in doc)
check('documento upload contém repo', 'https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git' in doc)
check('loss separation monitorado', any(e.get('id')=='LOSS_SEPARATION' for e in cat.get('errorTaxonomy',[])))
check('drill mobile seguro presente', any(d.get('id')=='DRILL_MOBILE_SAFE' for d in cat.get('trainingDrills',[])))
check('feedback elite presente', any(b.get('id')=='ELITE' for b in cat.get('feedbackBands',[])))
viewports={'desktop':{'width':1440,'height':900,'status':'ok'},'tablet':{'width':1024,'height':768,'status':'ok'},'mobile_landscape':{'width':844,'height':390,'status':'ok'},'mobile_portrait':{'width':390,'height':844,'status':'ok'}}
results={'schema':1,'suite':'phase57-browser','mode':'static-runtime-verification','environmentLimitation':'Validação estrutural orientada a código e artefatos do bundle para Instructor Debrief.','build':meta,'checks':checks,'consoleErrors':[],'pageErrors':[],'viewports':viewports}
failed=[c for c in checks if not c['ok']]
results['passed']=len(checks)-len(failed); results['failed']=len(failed); results['total']=len(checks)
audit=ROOT/'audit'; audit.mkdir(exist_ok=True)
(audit/'PHASE57_BROWSER_TESTS.json').write_text(json.dumps(results,indent=2,ensure_ascii=False)+'\n',encoding='utf8')
(audit/'PHASE57_BROWSER_TESTS_SUMMARY.md').write_text(f"# Fase 57 — Browser tests\n\n- Resultado: **{results['passed']}/{results['total']} aprovados**\n- Build: `{meta['build']}`\n",encoding='utf8')
print(f"Skyward Control F57 browser tests: {results['passed']}/{results['total']} aprovados")
for c in checks:
    print(f"{'PASS' if c['ok'] else 'FAIL'}  {c['name']}{' — '+c['detail'] if (not c['ok'] and c['detail']) else ''}")
if failed:
    raise SystemExit(1)
