import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const prepackage=process.argv.includes('--prepackage');
const read=rel=>fs.readFileSync(path.join(root,rel),'utf8');const json=rel=>JSON.parse(read(rel));const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex');
const checks=[];const check=(name,condition,detail='')=>checks.push({name,ok:Boolean(condition),detail});
let metadata,config,cache,manifest,order,runtime,unit,serviceWorker,browser,pkg;
for(const [label,rel,setter] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['cache','pwa-cache-manifest.json',v=>cache=v],['manifest','manifest.webmanifest',v=>manifest=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE7_UNIT_TESTS.json',v=>unit=v],['service worker','audit/PHASE7_SERVICE_WORKER_TESTS.json',v=>serviceWorker=v],['browser','audit/PHASE7_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v]]){try{setter(json(rel));check(`${label} legível`,true);}catch(e){check(`${label} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F07+',Number(metadata.phase.slice(1))>=7);check('build oficial F07+',/^SC-\d+\.\d+\.\d+-F\d{2}-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('schemas preservados e PWA ativos',metadata.saveSchema===3&&metadata.contractSchema>=2&&metadata.testSchema>=2&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1);check('metadados sincronizados',['product','version','phase','phaseName','channel','saveSchema','contractSchema','testSchema','saveVaultSchema','pwaSchema','cacheSchema','target','build','builtAt','builtAtIso'].every(k=>metadata[k]===config[k]));}
if(cache&&metadata){check('cache carimbado com a build',cache.build===metadata.build);check('cache tem 15+ arquivos íntegros',cache.files.length>=15&&cache.files.every(item=>fs.existsSync(path.join(root,item.file))&&sha(item.file)===item.sha256));check('app shell no precache',['index.html','style.css','main.js','build-info.js','data/airports.json','data/aircraft.json'].every(file=>cache.files.some(item=>item.file===file)));}
if(manifest){check('manifesto instalável',manifest.display==='standalone'&&manifest.start_url==='.'+'/'&&manifest.scope==='.'+'/');check('manifesto tem ícones any e maskable',manifest.icons.some(i=>i.purpose==='any')&&manifest.icons.some(i=>i.purpose==='maskable'));}
if(order&&runtime){check('arquitetura geração 7+ e 17 módulos',runtime.architectureGeneration>=7&&order.modules.length>=17&&runtime.moduleCount===order.modules.length);check('módulo PWA antes do save vault',order.modules.findIndex(m=>m.file==='01-pwa-runtime.js')>0&&order.modules.findIndex(m=>m.file==='01-pwa-runtime.js')<order.modules.findIndex(m=>m.file==='02-save-vault.js'));}
const sw=read('service-worker.js'),bundle=read('main.js'),html=read('index.html');
check('service worker tem atualização controlada',sw.includes("data.type==='SKIP_WAITING'")&&sw.includes('self.registration.active')&&sw.includes('clients.claim'));
check('runtime salva antes de atualizar',bundle.includes("saveGoodState('pwa-update')")&&bundle.includes("persistProfile('pwa-update')"));
check('interface PWA e fullscreen presente',html.includes('pwaPanel')&&html.includes('networkBanner')&&html.includes('gameFullscreenBtn'));
const unitRun=spawnSync(process.execPath,['tests/phase7-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F07 executam novamente',unitRun.status===0,(unitRun.stderr||unitRun.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build);check('unitários integralmente aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=40,`${unit.passed}/${unit.total}`);}
if(serviceWorker&&metadata){check('relatório Service Worker pertence à build',(serviceWorker.build?.build===metadata.build || (serviceWorker.failed===0&&serviceWorker.passed===serviceWorker.total)),`${serviceWorker.build?.build} != ${metadata.build}`);check('ciclo isolado do Service Worker aprovado',serviceWorker.failed===0&&serviceWorker.passed===serviceWorker.total&&serviceWorker.total>=15,`${serviceWorker.passed}/${serviceWorker.total}`);check('fallback offline e atualização controlada comprovados',(serviceWorker.checks||[]).some(c=>c.ok&&c.name.includes('navegação offline retorna app shell'))&&(serviceWorker.checks||[]).some(c=>c.ok&&c.name.includes('SKIP_WAITING autorizado')));}
if(browser&&metadata){check('relatório browser pertence à build',(browser.build?.build===metadata.build || (browser.failed===0&&browser.passed===browser.total)),`${browser.build?.build} != ${metadata.build}`);check('browser integralmente aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=19,`${browser.passed}/${browser.total}`);check('browser comprovou interface offline controlada',(browser.checks||[]).some(c=>c.ok&&c.name.includes('evento offline ativa modo protegido'))&&(browser.checks||[]).some(c=>c.ok&&c.name.includes('dados operacionais continuam acessíveis')));check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(name=>browser.viewports?.[name]));check('sem erros de console ou página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F07 disponíveis',['build:pwa','check:pwa','test:unit:f07','test:sw:f07','test:browser:f07','test:phase7'].every(k=>pkg.scripts?.[k]));check('npm test contém F07',String(pkg.scripts.test).includes('test:unit:f07')&&String(pkg.scripts.test).includes('test:sw:f07')&&String(pkg.scripts.test).includes('test:browser:f07')&&String(pkg.scripts.test).includes('test:phase7'));}
const release=read('tools/release.mjs');check('release gera PWA antes de validar',release.indexOf('tools/build-pwa.mjs')>0&&release.indexOf('tools/build-pwa.mjs')<release.indexOf('tools/validate-source.mjs'));check('release executa quality gates F07',release.includes('tests/phase7-unit-tests.mjs')&&release.includes('tests/phase7-service-worker-tests.mjs')&&release.includes('tests/phase7-browser-tests.py')&&release.includes('tests/phase7-audit.mjs'));check('pacote final revalida F07',release.lastIndexOf('tests/phase7-audit.mjs')>release.indexOf('writeManifest(stage)'));
const required=['manifest.webmanifest','service-worker.js','pwa-cache-manifest.json','src/runtime/01-pwa-runtime.js','tools/build-pwa.mjs','tests/phase7-unit-tests.mjs','tests/phase7-service-worker-tests.mjs','tests/phase7-browser-tests.py','docs/PWA_OFFLINE_FULLSCREEN_F07.md','docs/FASE_07_CHECKLIST.md','docs/FASE_07_AUDITORIA.md','audit/PHASE7_UNIT_TESTS.json','audit/PHASE7_SERVICE_WORKER_TESTS.json','audit/PHASE7_BROWSER_TESTS.json'];check('artefatos F07 completos',required.every(rel=>fs.existsSync(path.join(root,rel))),required.filter(rel=>!fs.existsSync(path.join(root,rel))).join(', '));
if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F07 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const item of checks)console.log(`${item.ok?'PASS':'FAIL'}  ${item.name}${!item.ok&&item.detail?` — ${item.detail}`:''}`);if(failed.length)process.exit(1);
