import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE24_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE24_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/gold-master-package.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F24',metadata.version==='1.24.0'&&metadata.phase==='F24');check('build oficial F24',/^SC-1\.24\.0-F24-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('gold master schema 1',metadata.goldMasterSchema===1&&config.goldMasterSchema===1);check('canal gold-master',metadata.channel==='gold-master'&&config.channel==='gold-master');check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1&&metadata.releaseCandidateSchema===1);}
if(order&&runtime){check('arquitetura geração 24',runtime.architectureGeneration===24);check('33 módulos oficiais',order.modules.length>=33&&runtime.moduleCount===order.modules.length);check('módulo GM antes de tráfego',order.modules.findIndex(m=>m.file==='27-gold-master-package.js')>=0&&order.modules.findIndex(m=>m.file==='27-gold-master-package.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F24 registrada',String(runtime.strategy).includes('gold-master-packaging'));}
const source=read('src/runtime/27-gold-master-package.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F24 integrado',source.includes('GOLD_MASTER_CATALOG')&&source.includes('window.SKYWARD_GOLD_MASTER=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.goldMasterGates?.length>=9&&catalog.manualSections?.length>=10&&catalog.storeChecklist?.length>=8);
check('GM conectado ao início',traffic.includes('initializeGoldMasterPackage'));
check('fim de turno avalia GM',ui.includes('evaluateGoldMasterShift'));
check('UI final mostra GM',ui.includes('Gold Master')&&ui.includes('GM Score'));
check('CSS painel GM',style.includes('.gold-master-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 27-gold-master-package')&&bundle.includes('SKYWARD_GOLD_MASTER'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/gold-master-package.json'));
check('manual e QA GM existem',fs.existsSync(path.join(root,'docs/PLAYER_MANUAL_F24.md'))&&fs.existsSync(path.join(root,'docs/GOLD_MASTER_QA_F24.md'))&&fs.existsSync(path.join(root,'docs/STORE_PWA_CHECKLIST_F24.md')));
check('release notes GM existem',fs.existsSync(path.join(root,'docs/PUBLIC_RELEASE_NOTES_F24_GOLD_MASTER.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
const run=spawnSync(process.execPath,['tests/phase24-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F24 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=14,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F24 disponíveis',['test:unit:f24','test:browser:f24','test:phase24'].every(k=>pkg.scripts?.[k]));check('npm test contém F24',String(pkg.scripts.test).includes('test:unit:f24')&&String(pkg.scripts.test).includes('test:browser:f24')&&String(pkg.scripts.test).includes('test:phase24'));}
const required=['src/runtime/27-gold-master-package.js','data/gold-master-package.json','tests/phase24-unit-tests.mjs','tests/phase24-browser-tests.py','tests/phase24-audit.mjs','docs/PLAYER_MANUAL_F24.md','docs/GOLD_MASTER_QA_F24.md','docs/STORE_PWA_CHECKLIST_F24.md','docs/FASE_24_CHECKLIST.md','docs/FASE_24_AUDITORIA.md','docs/PUBLIC_RELEASE_NOTES_F24_GOLD_MASTER.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE24_UNIT_TESTS.json','audit/PHASE24_BROWSER_TESTS.json'];check('artefatos F24 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F24 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
