import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE49_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE49_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/terminal-flow.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F49',metadata.version==='1.49.0'&&metadata.phase==='F49');check('build oficial F49',/^SC-1\.49\.0-F49-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('terminal flow schema 1',metadata.terminalFlowSchema===1&&config.terminalFlowSchema===1);check('canal terminal-flow',metadata.channel==='terminal-flow'&&config.channel==='terminal-flow');check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1&&metadata.releaseCandidateSchema===1&&metadata.goldMasterSchema===1&&metadata.postGoldMasterSchema===1&&metadata.postPublishHealthSchema===1&&metadata.publicOpsSchema===1&&metadata.trainingAcademySchema===1&&metadata.trainingCoachSchema===1&&metadata.internationalCampaignSchema===1&&metadata.airlineOpsSchema===1&&metadata.airportAuthoritySchema===1&&metadata.crisisCommandSchema===1&&metadata.safetyComplianceSchema===1&&metadata.infrastructureExpansionSchema===1&&metadata.environmentSustainabilitySchema===1&&metadata.revenueManagementSchema===1&&metadata.workforceStaffingSchema===1&&metadata.passengerReputationSchema===1&&metadata.multiAirportNetworkSchema===1&&metadata.emergencyResponseSchema===1&&metadata.securityCyberDefenseSchema===1&&metadata.assetMaintenanceSchema===1&&metadata.digitalTwinPredictiveSchema===1&&metadata.aiCopilotSchema===1&&metadata.radioPhraseologySchema===1&&metadata.groundTurnaroundSchema===1&&metadata.cargoLogisticsSchema===1);}
if(order&&runtime){check('arquitetura geração 49',runtime.architectureGeneration===49);check('58 módulos oficiais',order.modules.length>=58&&runtime.moduleCount===order.modules.length);check('módulo terminal antes de tráfego',order.modules.findIndex(m=>m.file==='52-terminal-flow-landside-center.js')>=0&&order.modules.findIndex(m=>m.file==='52-terminal-flow-landside-center.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F49 registrada',String(runtime.strategy).includes('terminal-flow-landside-center'));}
const source=read('src/runtime/52-terminal-flow-landside-center.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F49 integrado',source.includes('TERMINAL_FLOW_CATALOG')&&source.includes('window.SKYWARD_TERMINAL_FLOW=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.terminalZones?.length>=9&&catalog.queueIncidents?.length>=8&&catalog.flowPrograms?.length>=8);
check('F49 conectado ao início',traffic.includes('initializeTerminalFlow'));
check('UI final mostra Terminal Flow',ui.includes('Terminal Flow')&&ui.includes('Fila Média'));
check('CSS painel Terminal',style.includes('.terminal-flow-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 52-terminal-flow-landside-center')&&bundle.includes('SKYWARD_TERMINAL_FLOW'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/terminal-flow.json'));
check('docs F49 existem',fs.existsSync(path.join(root,'docs/TERMINAL_FLOW_F49.md'))&&fs.existsSync(path.join(root,'docs/CHECKIN_SEGURANCA_IMIGRACAO_BAGAGEM_F49.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
check('terminal possui segurança/bagagem',catalog.terminalZones.some(z=>z.id==='SECURITY_QUEUE')&&catalog.terminalZones.some(z=>z.id==='BAGGAGE_CLAIM'));
const run=spawnSync(process.execPath,['tests/phase49-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F49 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=14,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=22,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F49 disponíveis',['test:unit:f49','test:browser:f49','test:phase49'].every(k=>pkg.scripts?.[k]));check('npm test contém F49',String(pkg.scripts.test).includes('test:unit:f49')&&String(pkg.scripts.test).includes('test:browser:f49')&&String(pkg.scripts.test).includes('test:phase49'));}
const required=['src/runtime/52-terminal-flow-landside-center.js','data/terminal-flow.json','tests/phase49-unit-tests.mjs','tests/phase49-browser-tests.py','tests/phase49-audit.mjs','docs/TERMINAL_FLOW_F49.md','docs/CHECKIN_SEGURANCA_IMIGRACAO_BAGAGEM_F49.md','docs/FASE_49_CHECKLIST.md','docs/FASE_49_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE49_UNIT_TESTS.json','audit/PHASE49_BROWSER_TESTS.json'];check('artefatos F49 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F49 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
