import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE11_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE11_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F11+',/^F(1[1-9]|[2-9][0-9])$/.test(metadata.phase));check('build oficial F11+',/^SC-\d+\.\d+\.\d+-F\d{2}-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('replay schema 1',metadata.replaySchema===1&&config.replaySchema===1);check('schemas anteriores preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1);check('metadados sincronizados',['product','version','phase','phaseName','channel','saveSchema','contractSchema','testSchema','saveVaultSchema','pwaSchema','cacheSchema','uxSchema','desktopSchema','accessibilitySchema','replaySchema','target','build','builtAt','builtAtIso'].every(k=>metadata[k]===config[k]));}
if(order&&runtime){check('arquitetura geração 11+',runtime.architectureGeneration>=11);check('20+ módulos oficiais',order.modules.length>=20&&runtime.moduleCount===order.modules.length);check('módulo replay antes do bridge QA',order.modules.findIndex(m=>m.file==='14-deterministic-replay.js')>=0&&order.modules.findIndex(m=>m.file==='14-deterministic-replay.js')<order.modules.findIndex(m=>m.file==='12-quality-test-bridge.js'));check('estratégia F11 registrada',String(runtime.strategy).includes('deterministic-replay-clock'));}
const html=read('index.html'),css=read('style.css'),source=read('src/runtime/14-deterministic-replay.js'),bundle=read('main.js');
check('painel F11 integrado',html.includes('replayPanel')&&html.includes('data-replay-schema="1"')&&html.includes('replayBadge'));
check('CSS F11 integrado',css.includes('.replay-panel')&&css.includes('.atc-replay'));
check('API congelada',source.includes('window.SKYWARD_REPLAY=Object.freeze'));
check('seed determinística',source.includes('replaySeedFromProfile')&&source.includes('replayMulberry32'));
check('relógio lógico',source.includes('replayStep')&&source.includes('replayElapsedSeconds'));
check('checksum e exportação',source.includes('replayChecksum')&&source.includes('replayExport')&&source.includes('replayImport'));
check('wrappers conectados',source.includes('startGame=function')&&source.includes('command=function'));
check('bundle sincronizado',bundle.includes('@skyward-module 14-deterministic-replay')&&bundle.includes('SKYWARD_REPLAY'));
check('simulação usa replay clock',bundle.includes('SKYWARD_REPLAY?.step')&&bundle.includes('SKYWARD_REPLAY?.elapsed'));
check('aleatoriedade direcionada',bundle.includes('skywardRandomUnit()<arrChance')&&bundle.includes('skywardRandomUnit()>0.18'));
const run=spawnSync(process.execPath,['tests/phase11-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F11 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build ou é regressão aprovada',unit.build===metadata.build || (unit.failed===0&&unit.passed===unit.total),`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=20,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build ou é regressão aprovada',browser.build?.build===metadata.build || (browser.failed===0&&browser.passed===browser.total),`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));check('checkpoint comprovado',(browser.checks||[]).some(c=>c.ok&&c.name.includes('checkpoint manual')));check('import comprovado',(browser.checks||[]).some(c=>c.ok&&c.name.includes('import do próprio replay')));}
if(pkg){check('scripts F11 disponíveis',['test:unit:f11','test:browser:f11','test:phase11'].every(k=>pkg.scripts?.[k]));check('npm test contém F11',String(pkg.scripts.test).includes('test:unit:f11')&&String(pkg.scripts.test).includes('test:browser:f11')&&String(pkg.scripts.test).includes('test:phase11'));}
const release=read('tools/release.mjs');check('pipeline executa F11',release.includes('tests/phase11-unit-tests.mjs')&&release.includes('tests/phase11-browser-tests.py')&&release.includes('tests/phase11-audit.mjs'));check('pacote revalida F11',release.lastIndexOf('tests/phase11-audit.mjs')>release.indexOf('writeManifest(stage)'));
const required=['src/runtime/14-deterministic-replay.js','tests/phase11-unit-tests.mjs','tests/phase11-browser-tests.py','tests/phase11-audit.mjs','docs/RELOGIO_DETERMINISTICO_REPLAY_F11.md','docs/FASE_11_CHECKLIST.md','docs/FASE_11_AUDITORIA.md','audit/PHASE11_UNIT_TESTS.json','audit/PHASE11_BROWSER_TESTS.json'];check('artefatos F11 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F11 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
