import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE45_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE45_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/ai-copilot-decision-support.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F45',metadata.version==='1.45.0'&&metadata.phase==='F45');check('build oficial F45',/^SC-1\.45\.0-F45-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('ai copilot schema 1',metadata.aiCopilotSchema===1&&config.aiCopilotSchema===1);check('canal ai-copilot-decision-support',metadata.channel==='ai-copilot-decision-support'&&config.channel==='ai-copilot-decision-support');check('schemas preservados',metadata.digitalTwinPredictiveSchema===1&&metadata.assetMaintenanceSchema===1&&metadata.securityCyberDefenseSchema===1&&metadata.emergencyResponseSchema===1&&metadata.multiAirportNetworkSchema===1&&metadata.passengerReputationSchema===1&&metadata.workforceStaffingSchema===1&&metadata.revenueManagementSchema===1&&metadata.safetyComplianceSchema===1);}
if(order&&runtime){check('arquitetura geração 45',runtime.architectureGeneration===45);check('53 módulos oficiais',order.modules.length>=53&&runtime.moduleCount===order.modules.length);check('módulo ai antes de tráfego',order.modules.findIndex(m=>m.file==='48-ai-copilot-decision-support-center.js')>=0&&order.modules.findIndex(m=>m.file==='48-ai-copilot-decision-support-center.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F45 registrada',String(runtime.strategy).includes('ai-copilot-decision-support-center'));}
const source=read('src/runtime/48-ai-copilot-decision-support-center.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F45 integrado',source.includes('AI_COPILOT_CATALOG')&&source.includes('window.SKYWARD_AI_COPILOT=Object.freeze'));check('catálogo completo',catalog?.schema===1&&catalog.copilotDomains?.length>=10&&catalog.recommendationRules?.length>=10&&catalog.copilotModes?.length>=4);check('F45 conectado ao início',traffic.includes('initializeAiCopilot'));check('UI final mostra AI Copilot',ui.includes('AI Copilot')&&ui.includes('Conf. IA'));check('CSS painel AI',style.includes('.ai-copilot-inline'));check('bundle sincronizado',bundle.includes('@skyward-module 48-ai-copilot-decision-support-center')&&bundle.includes('SKYWARD_AI_COPILOT'));check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/ai-copilot-decision-support.json'));check('docs F45 existem',fs.existsSync(path.join(root,'docs/AI_COPILOT_DECISION_SUPPORT_F45.md'))&&fs.existsSync(path.join(root,'docs/RECOMENDACOES_ALERTAS_PLANO_ACAO_F45.md')));check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));check('copilot possui traffic/assets',catalog.copilotDomains.some(d=>d.id==='TRAFFIC')&&catalog.copilotDomains.some(d=>d.id==='ASSETS'));
const run=spawnSync(process.execPath,['tests/phase45-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F45 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=15,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F45 disponíveis',['test:unit:f45','test:browser:f45','test:phase45'].every(k=>pkg.scripts?.[k]));check('npm test contém F45',String(pkg.scripts.test).includes('test:unit:f45')&&String(pkg.scripts.test).includes('test:browser:f45')&&String(pkg.scripts.test).includes('test:phase45'));}
const required=['src/runtime/48-ai-copilot-decision-support-center.js','data/ai-copilot-decision-support.json','tests/phase45-unit-tests.mjs','tests/phase45-browser-tests.py','tests/phase45-audit.mjs','docs/AI_COPILOT_DECISION_SUPPORT_F45.md','docs/RECOMENDACOES_ALERTAS_PLANO_ACAO_F45.md','docs/FASE_45_CHECKLIST.md','docs/FASE_45_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE45_UNIT_TESTS.json','audit/PHASE45_BROWSER_TESTS.json'];check('artefatos F45 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F45 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
