import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE58_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE58_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/replay-timeline-heatmap.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F58',metadata.version==='1.58.0'&&metadata.phase==='F58');check('build oficial F58',/^SC-1\.58\.0-F58-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('replay timeline schema 1',metadata.replayTimelineSchema===1&&config.replayTimelineSchema===1);check('canal replay-timeline-heatmap',metadata.channel==='replay-timeline-heatmap'&&config.channel==='replay-timeline-heatmap');check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1&&metadata.releaseCandidateSchema===1&&metadata.goldMasterSchema===1&&metadata.postGoldMasterSchema===1&&metadata.postPublishHealthSchema===1&&metadata.publicOpsSchema===1&&metadata.trainingAcademySchema===1&&metadata.trainingCoachSchema===1&&metadata.internationalCampaignSchema===1&&metadata.airlineOpsSchema===1&&metadata.airportAuthoritySchema===1&&metadata.crisisCommandSchema===1&&metadata.safetyComplianceSchema===1&&metadata.infrastructureExpansionSchema===1&&metadata.environmentSustainabilitySchema===1&&metadata.revenueManagementSchema===1&&metadata.workforceStaffingSchema===1&&metadata.passengerReputationSchema===1&&metadata.multiAirportNetworkSchema===1&&metadata.emergencyResponseSchema===1&&metadata.securityCyberDefenseSchema===1&&metadata.assetMaintenanceSchema===1&&metadata.digitalTwinPredictiveSchema===1&&metadata.aiCopilotSchema===1&&metadata.radioPhraseologySchema===1&&metadata.groundTurnaroundSchema===1&&metadata.cargoLogisticsSchema===1&&metadata.terminalFlowSchema===1&&metadata.nonAeroRevenueSchema===1&&metadata.adaptivePaceSchema===1&&metadata.stabilityDiagnosticsSchema===1&&metadata.pwaUpdateManagerSchema===1&&metadata.liveOpsRemoteConfigSchema===1&&metadata.scenarioMissionSchema===1&&metadata.campaignProgressionSchema===1&&metadata.instructorDebriefSchema===1);}
if(order&&runtime){check('arquitetura geração 58',runtime.architectureGeneration===58);check('67 módulos oficiais',order.modules.length>=67&&runtime.moduleCount===order.modules.length);check('módulo replay antes de tráfego',order.modules.findIndex(m=>m.file==='61-replay-timeline-heatmap-center.js')>=0&&order.modules.findIndex(m=>m.file==='61-replay-timeline-heatmap-center.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F58 registrada',String(runtime.strategy).includes('replay-timeline-heatmap-center'));}
const source=read('src/runtime/61-replay-timeline-heatmap-center.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css'),notes=read('BUILD_NOTES.md');
check('módulo F58 integrado',source.includes('REPLAY_TIMELINE_CATALOG')&&source.includes('window.SKYWARD_REPLAY_TIMELINE=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.timelineTracks?.length>=8&&catalog.bookmarkTypes?.length>=10&&catalog.heatmapZones?.length>=8);
check('F58 conectado ao início',traffic.includes('initializeReplayTimeline'));
check('UI final mostra Replay',ui.includes('Replay')&&ui.includes('Heatmap'));
check('CSS painel Replay',style.includes('.replay-timeline-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 61-replay-timeline-heatmap-center')&&bundle.includes('SKYWARD_REPLAY_TIMELINE'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/replay-timeline-heatmap.json'));
check('docs F58 existem',fs.existsSync(path.join(root,'docs/REPLAY_TIMELINE_HEATMAP_F58.md'))&&fs.existsSync(path.join(root,'docs/BOOKMARKS_HEATMAP_SESSION_EXPORT_F58.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
check('F50.1 preservado',notes.includes('F50.1')||read('CHANGELOG.md').includes('F50.1'));
check('F51 preservado',metadata.adaptivePaceSchema===1&&bundle.includes('SKYWARD_ADAPTIVE_PACE'));
check('F52 preservado',metadata.stabilityDiagnosticsSchema===1&&bundle.includes('SKYWARD_STABILITY_DIAGNOSTICS'));
check('F53 preservado',metadata.pwaUpdateManagerSchema===1&&bundle.includes('SKYWARD_PWA_UPDATE_MANAGER'));
check('F54 preservado',metadata.liveOpsRemoteConfigSchema===1&&bundle.includes('SKYWARD_LIVE_OPS_CONFIG'));
check('F55 preservado',metadata.scenarioMissionSchema===1&&bundle.includes('SKYWARD_SCENARIO_MISSION'));
check('F56 preservado',metadata.campaignProgressionSchema===1&&bundle.includes('SKYWARD_CAMPAIGN_PROGRESSION'));
check('F57 preservado',metadata.instructorDebriefSchema===1&&bundle.includes('SKYWARD_INSTRUCTOR_DEBRIEF'));
check('replay essencial presente',catalog.bookmarkTypes.some(b=>b.id==='LOSS_SEPARATION')&&catalog.heatmapZones.some(z=>z.id==='WORKLOAD')&&catalog.exportProfiles.some(p=>p.id==='INSTRUCTOR_FULL'));
const run=spawnSync(process.execPath,['tests/phase58-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F58 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=14,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=30,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F58 disponíveis',['test:unit:f58','test:browser:f58','test:phase58'].every(k=>pkg.scripts?.[k]));check('npm test contém F58',String(pkg.scripts.test).includes('test:unit:f58')&&String(pkg.scripts.test).includes('test:browser:f58')&&String(pkg.scripts.test).includes('test:phase58'));}
const required=['src/runtime/61-replay-timeline-heatmap-center.js','data/replay-timeline-heatmap.json','tests/phase58-unit-tests.mjs','tests/phase58-browser-tests.py','tests/phase58-audit.mjs','docs/REPLAY_TIMELINE_HEATMAP_F58.md','docs/BOOKMARKS_HEATMAP_SESSION_EXPORT_F58.md','docs/FASE_58_CHECKLIST.md','docs/FASE_58_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE58_UNIT_TESTS.json','audit/PHASE58_BROWSER_TESTS.json'];check('artefatos F58 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F58 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
