import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE60_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE60_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/dynamic-weather-atis-notam.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F60',metadata.version==='1.60.0'&&metadata.phase==='F60');check('build oficial F60',/^SC-1\.60\.0-F60-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('dynamic weather schema 1',metadata.dynamicWeatherAtisNotamSchema===1&&config.dynamicWeatherAtisNotamSchema===1);check('canal dynamic-weather-atis-notam',metadata.channel==='dynamic-weather-atis-notam'&&config.channel==='dynamic-weather-atis-notam');check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1&&metadata.releaseCandidateSchema===1&&metadata.goldMasterSchema===1&&metadata.postGoldMasterSchema===1&&metadata.postPublishHealthSchema===1&&metadata.publicOpsSchema===1&&metadata.trainingAcademySchema===1&&metadata.trainingCoachSchema===1&&metadata.internationalCampaignSchema===1&&metadata.airlineOpsSchema===1&&metadata.airportAuthoritySchema===1&&metadata.crisisCommandSchema===1&&metadata.safetyComplianceSchema===1&&metadata.infrastructureExpansionSchema===1&&metadata.environmentSustainabilitySchema===1&&metadata.revenueManagementSchema===1&&metadata.workforceStaffingSchema===1&&metadata.passengerReputationSchema===1&&metadata.multiAirportNetworkSchema===1&&metadata.emergencyResponseSchema===1&&metadata.securityCyberDefenseSchema===1&&metadata.assetMaintenanceSchema===1&&metadata.digitalTwinPredictiveSchema===1&&metadata.aiCopilotSchema===1&&metadata.radioPhraseologySchema===1&&metadata.groundTurnaroundSchema===1&&metadata.cargoLogisticsSchema===1&&metadata.terminalFlowSchema===1&&metadata.nonAeroRevenueSchema===1&&metadata.adaptivePaceSchema===1&&metadata.stabilityDiagnosticsSchema===1&&metadata.pwaUpdateManagerSchema===1&&metadata.liveOpsRemoteConfigSchema===1&&metadata.scenarioMissionSchema===1&&metadata.campaignProgressionSchema===1&&metadata.instructorDebriefSchema===1&&metadata.replayTimelineSchema===1&&metadata.worldAirportProcedureSchema===1);}
if(order&&runtime){check('arquitetura geração 60',runtime.architectureGeneration===60);check('69 módulos oficiais',order.modules.length>=69&&runtime.moduleCount===order.modules.length);check('módulo weather antes de tráfego',order.modules.findIndex(m=>m.file==='63-dynamic-weather-atis-notam-center.js')>=0&&order.modules.findIndex(m=>m.file==='63-dynamic-weather-atis-notam-center.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F60 registrada',String(runtime.strategy).includes('dynamic-weather-atis-notam-center'));}
const source=read('src/runtime/63-dynamic-weather-atis-notam-center.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css'),notes=read('BUILD_NOTES.md');
check('módulo F60 integrado',source.includes('DYNAMIC_WEATHER_ATIS_NOTAM_CATALOG')&&source.includes('window.SKYWARD_DYNAMIC_WEATHER=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.weatherPhenomena?.length>=8&&catalog.atisTemplates?.length>=5&&catalog.notamTypes?.length>=7);
check('F60 conectado ao início',traffic.includes('initializeDynamicWeather'));
check('UI final mostra Weather',ui.includes('Weather')&&ui.includes('ATIS'));
check('CSS painel Weather',style.includes('.dynamic-weather-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 63-dynamic-weather-atis-notam-center')&&bundle.includes('SKYWARD_DYNAMIC_WEATHER'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/dynamic-weather-atis-notam.json'));
check('docs F60 existem',fs.existsSync(path.join(root,'docs/DYNAMIC_WEATHER_ATIS_NOTAM_F60.md'))&&fs.existsSync(path.join(root,'docs/WEATHER_RADAR_ATIS_NOTAM_IMPACT_F60.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
check('F50.1 preservado',notes.includes('F50.1')||read('CHANGELOG.md').includes('F50.1'));
check('F51 preservado',metadata.adaptivePaceSchema===1&&bundle.includes('SKYWARD_ADAPTIVE_PACE'));
check('F52 preservado',metadata.stabilityDiagnosticsSchema===1&&bundle.includes('SKYWARD_STABILITY_DIAGNOSTICS'));
check('F53 preservado',metadata.pwaUpdateManagerSchema===1&&bundle.includes('SKYWARD_PWA_UPDATE_MANAGER'));
check('F54 preservado',metadata.liveOpsRemoteConfigSchema===1&&bundle.includes('SKYWARD_LIVE_OPS_CONFIG'));
check('F55 preservado',metadata.scenarioMissionSchema===1&&bundle.includes('SKYWARD_SCENARIO_MISSION'));
check('F56 preservado',metadata.campaignProgressionSchema===1&&bundle.includes('SKYWARD_CAMPAIGN_PROGRESSION'));
check('F57 preservado',metadata.instructorDebriefSchema===1&&bundle.includes('SKYWARD_INSTRUCTOR_DEBRIEF'));
check('F58 preservado',metadata.replayTimelineSchema===1&&bundle.includes('SKYWARD_REPLAY_TIMELINE'));
check('F59 preservado',metadata.worldAirportProcedureSchema===1&&bundle.includes('SKYWARD_WORLD_AIRPORTS'));
check('weather essentials presentes',catalog.weatherPhenomena.some(w=>w.id==='CROSSWIND_ALERT')&&catalog.notamTypes.some(n=>n.id==='RUNWAY_PARTIAL_CLOSURE')&&catalog.atisTemplates.some(a=>a.id==='INFO_DELTA'));
const run=spawnSync(process.execPath,['tests/phase60-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F60 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=14,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=32,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F60 disponíveis',['test:unit:f60','test:browser:f60','test:phase60'].every(k=>pkg.scripts?.[k]));check('npm test contém F60',String(pkg.scripts.test).includes('test:unit:f60')&&String(pkg.scripts.test).includes('test:browser:f60')&&String(pkg.scripts.test).includes('test:phase60'));}
const required=['src/runtime/63-dynamic-weather-atis-notam-center.js','data/dynamic-weather-atis-notam.json','tests/phase60-unit-tests.mjs','tests/phase60-browser-tests.py','tests/phase60-audit.mjs','docs/DYNAMIC_WEATHER_ATIS_NOTAM_F60.md','docs/WEATHER_RADAR_ATIS_NOTAM_IMPACT_F60.md','docs/FASE_60_CHECKLIST.md','docs/FASE_60_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE60_UNIT_TESTS.json','audit/PHASE60_BROWSER_TESTS.json'];check('artefatos F60 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F60 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
