import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE12_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE12_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/aircraft-performance.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F12',metadata.version==='1.12.0'&&metadata.phase==='F12');check('build oficial F12',/^SC-1\.12\.0-F12-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('aircraft performance schema 1',metadata.aircraftPerformanceSchema===1&&config.aircraftPerformanceSchema===1);check('schemas anteriores preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1);check('metadados sincronizados',['product','version','phase','phaseName','channel','saveSchema','contractSchema','testSchema','saveVaultSchema','pwaSchema','cacheSchema','uxSchema','desktopSchema','accessibilitySchema','replaySchema','aircraftPerformanceSchema','target','build','builtAt','builtAtIso'].every(k=>metadata[k]===config[k]));}
if(order&&runtime){check('arquitetura geração 12',runtime.architectureGeneration===12);check('21 módulos oficiais',order.modules.length>=21&&runtime.moduleCount===order.modules.length);check('módulo performance antes de tráfego',order.modules.findIndex(m=>m.file==='15-aircraft-performance.js')>=0&&order.modules.findIndex(m=>m.file==='15-aircraft-performance.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F12 registrada',String(runtime.strategy).includes('realistic-aircraft-performance'));}
const source=read('src/runtime/15-aircraft-performance.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),sim=read('src/runtime/07-simulation-safety.js'),fuel=read('src/runtime/02-weather-fuel-operations.js');
check('módulo F12 integrado',source.includes('AIRCRAFT_PERFORMANCE_TABLE')&&source.includes('window.SKYWARD_AIRCRAFT_PERFORMANCE=Object.freeze'));
check('catálogo data-driven completo',catalog?.schema===1&&Object.keys(catalog.profiles||{}).length>=8);
check('perfis comerciais presentes',['A320','A20N','A321','B738','B739','B752','E190','B77W','C208'].every(t=>source.includes(`${t}:`)||JSON.stringify(catalog.profiles).includes(t)));
check('física por envelope conectada',sim.includes('updateAircraftPerformanceStep')&&sim.includes('aircraftLandingRisk'));
check('tráfego normaliza performance',read('src/runtime/06-traffic-requests.js').includes('normalizeAircraftPerformance'));
check('fuel usa multiplicador por aeronave',fuel.includes('aircraftFuelMultiplier'));
check('wake usa performance',fuel.includes('aircraftPerformanceProfile')&&fuel.includes('wakeCategory'));
check('UI mostra VREF e ENVELOPE',ui.includes('VREF')&&ui.includes('ENVELOPE'));
check('bundle sincronizado',bundle.includes('@skyward-module 15-aircraft-performance')&&bundle.includes('SKYWARD_AIRCRAFT_PERFORMANCE'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/aircraft-performance.json'));
const run=spawnSync(process.execPath,['tests/phase12-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F12 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=18,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=18,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));check('VREF comprovado',(browser.checks||[]).some(c=>c.ok&&c.name.includes('VREF')));}
if(pkg){check('scripts F12 disponíveis',['test:unit:f12','test:browser:f12','test:phase12'].every(k=>pkg.scripts?.[k]));check('npm test contém F12',String(pkg.scripts.test).includes('test:unit:f12')&&String(pkg.scripts.test).includes('test:browser:f12')&&String(pkg.scripts.test).includes('test:phase12'));}
const release=read('tools/release.mjs');check('pipeline executa F12',release.includes('tests/phase12-unit-tests.mjs')&&release.includes('tests/phase12-browser-tests.py')&&release.includes('tests/phase12-audit.mjs'));check('pacote revalida F12',release.lastIndexOf('tests/phase12-audit.mjs')>release.indexOf('writeManifest(stage)'));
const required=['src/runtime/15-aircraft-performance.js','data/aircraft-performance.json','tests/phase12-unit-tests.mjs','tests/phase12-browser-tests.py','tests/phase12-audit.mjs','docs/MODELO_REALISTA_AERONAVES_F12.md','docs/FASE_12_CHECKLIST.md','docs/FASE_12_AUDITORIA.md','audit/PHASE12_UNIT_TESTS.json','audit/PHASE12_BROWSER_TESTS.json'];check('artefatos F12 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F12 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
