import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE36_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE36_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/environment-sustainability.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F36',metadata.version==='1.36.0'&&metadata.phase==='F36');check('build oficial F36',/^SC-1\.36\.0-F36-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('environment sustainability schema 1',metadata.environmentSustainabilitySchema===1&&config.environmentSustainabilitySchema===1);check('canal environment-sustainability',metadata.channel==='environment-sustainability'&&config.channel==='environment-sustainability');check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1&&metadata.releaseCandidateSchema===1&&metadata.goldMasterSchema===1&&metadata.postGoldMasterSchema===1&&metadata.postPublishHealthSchema===1&&metadata.publicOpsSchema===1&&metadata.trainingAcademySchema===1&&metadata.trainingCoachSchema===1&&metadata.internationalCampaignSchema===1&&metadata.airlineOpsSchema===1&&metadata.airportAuthoritySchema===1&&metadata.crisisCommandSchema===1&&metadata.safetyComplianceSchema===1&&metadata.infrastructureExpansionSchema===1);}
if(order&&runtime){check('arquitetura geração 36',runtime.architectureGeneration===36);check('45 módulos oficiais',order.modules.length>=45&&runtime.moduleCount===order.modules.length);check('módulo environment antes de tráfego',order.modules.findIndex(m=>m.file==='39-environment-sustainability-center.js')>=0&&order.modules.findIndex(m=>m.file==='39-environment-sustainability-center.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F36 registrada',String(runtime.strategy).includes('environment-sustainability-center'));}
const source=read('src/runtime/39-environment-sustainability-center.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F36 integrado',source.includes('ENVIRONMENT_SUSTAINABILITY_CATALOG')&&source.includes('window.SKYWARD_ENVIRONMENT_SUSTAINABILITY=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.environmentMetrics?.length>=6&&catalog.greenInitiatives?.length>=6&&catalog.environmentEvents?.length>=5);
check('F36 conectado ao início',traffic.includes('initializeEnvironmentSustainability'));
check('UI final mostra ENV ESG',ui.includes('ENV ESG')&&ui.includes('Licença Amb.'));
check('CSS painel Environment',style.includes('.environment-sustainability-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 39-environment-sustainability-center')&&bundle.includes('SKYWARD_ENVIRONMENT_SUSTAINABILITY'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/environment-sustainability.json'));
check('docs F36 existem',fs.existsSync(path.join(root,'docs/ENVIRONMENT_SUSTAINABILITY_F36.md'))&&fs.existsSync(path.join(root,'docs/RUIDO_EMISSOES_COMUNIDADE_F36.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
check('environment possui ruído/CO2/CDA',catalog.environmentMetrics.some(m=>m.id==='NOISE')&&catalog.environmentMetrics.some(m=>m.id==='CO2')&&catalog.greenInitiatives.some(g=>g.id==='CDA_APPROACH'));
const run=spawnSync(process.execPath,['tests/phase36-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F36 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=15,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F36 disponíveis',['test:unit:f36','test:browser:f36','test:phase36'].every(k=>pkg.scripts?.[k]));check('npm test contém F36',String(pkg.scripts.test).includes('test:unit:f36')&&String(pkg.scripts.test).includes('test:browser:f36')&&String(pkg.scripts.test).includes('test:phase36'));}
const required=['src/runtime/39-environment-sustainability-center.js','data/environment-sustainability.json','tests/phase36-unit-tests.mjs','tests/phase36-browser-tests.py','tests/phase36-audit.mjs','docs/ENVIRONMENT_SUSTAINABILITY_F36.md','docs/RUIDO_EMISSOES_COMUNIDADE_F36.md','docs/FASE_36_CHECKLIST.md','docs/FASE_36_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE36_UNIT_TESTS.json','audit/PHASE36_BROWSER_TESTS.json'];check('artefatos F36 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F36 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
