import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE23_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE23_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/release-candidate-qa.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F23',metadata.version==='1.23.0'&&metadata.phase==='F23');check('build oficial F23',/^SC-1\.23\.0-F23-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('release candidate schema 1',metadata.releaseCandidateSchema===1&&config.releaseCandidateSchema===1);check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1);}
if(order&&runtime){check('arquitetura geração 23',runtime.architectureGeneration===23);check('32 módulos oficiais',order.modules.length>=32&&runtime.moduleCount===order.modules.length);check('módulo RC antes de tráfego',order.modules.findIndex(m=>m.file==='26-release-candidate-qa.js')>=0&&order.modules.findIndex(m=>m.file==='26-release-candidate-qa.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F23 registrada',String(runtime.strategy).includes('public-release-candidate-qa'));}
const source=read('src/runtime/26-release-candidate-qa.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F23 integrado',source.includes('RELEASE_CANDIDATE_CATALOG')&&source.includes('window.SKYWARD_RELEASE_CANDIDATE=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.rcGates?.length>=10&&catalog.guidedTutorial?.length>=8&&catalog.publicationChecklist?.length>=6);
check('RC conectado ao início',traffic.includes('initializeReleaseCandidateQA'));
check('fim de turno avalia RC',ui.includes('evaluateReleaseCandidateShift'));
check('UI final mostra RC/QA',ui.includes('Release Candidate')&&ui.includes('QA Score'));
check('CSS painel/tutorial RC',style.includes('.release-candidate-inline')&&style.includes('release-candidate-tutorial-overlay'));
check('bundle sincronizado',bundle.includes('@skyward-module 26-release-candidate-qa')&&bundle.includes('SKYWARD_RELEASE_CANDIDATE'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/release-candidate-qa.json'));
check('release notes públicas existem',fs.existsSync(path.join(root,'docs/PUBLIC_RELEASE_NOTES_F23.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
const run=spawnSync(process.execPath,['tests/phase23-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F23 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=15,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F23 disponíveis',['test:unit:f23','test:browser:f23','test:phase23'].every(k=>pkg.scripts?.[k]));check('npm test contém F23',String(pkg.scripts.test).includes('test:unit:f23')&&String(pkg.scripts.test).includes('test:browser:f23')&&String(pkg.scripts.test).includes('test:phase23'));}
const required=['src/runtime/26-release-candidate-qa.js','data/release-candidate-qa.json','tests/phase23-unit-tests.mjs','tests/phase23-browser-tests.py','tests/phase23-audit.mjs','docs/RELEASE_CANDIDATE_PUBLICA_F23.md','docs/FASE_23_CHECKLIST.md','docs/FASE_23_AUDITORIA.md','docs/PUBLIC_RELEASE_NOTES_F23.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE23_UNIT_TESTS.json','audit/PHASE23_BROWSER_TESTS.json'];check('artefatos F23 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F23 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
