import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE25_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE25_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/post-gold-master-publishing.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F25',metadata.version==='1.25.0'&&metadata.phase==='F25');check('build oficial F25',/^SC-1\.25\.0-F25-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('post gold master schema 1',metadata.postGoldMasterSchema===1&&config.postGoldMasterSchema===1);check('canal post-gold-master',metadata.channel==='post-gold-master'&&config.channel==='post-gold-master');check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1&&metadata.releaseCandidateSchema===1&&metadata.goldMasterSchema===1);}
if(order&&runtime){check('arquitetura geração 25',runtime.architectureGeneration===25);check('34 módulos oficiais',order.modules.length>=34&&runtime.moduleCount===order.modules.length);check('módulo post-GM antes de tráfego',order.modules.findIndex(m=>m.file==='28-post-gold-master-publishing.js')>=0&&order.modules.findIndex(m=>m.file==='28-post-gold-master-publishing.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F25 registrada',String(runtime.strategy).includes('post-gold-master-real-device-qa'));}
const source=read('src/runtime/28-post-gold-master-publishing.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F25 integrado',source.includes('POST_GOLD_MASTER_CATALOG')&&source.includes('window.SKYWARD_POST_GOLD_MASTER=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.realDeviceMatrix?.length>=5&&catalog.screenshotPlan?.length>=6&&catalog.publishingSteps?.length>=7);
check('Post-GM conectado ao início',traffic.includes('initializePostGoldMasterPublishing'));
check('UI final mostra Post-GM',ui.includes('Publicação PWA')&&ui.includes('Post-GM Ready'));
check('CSS painel Post-GM',style.includes('.post-gold-master-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 28-post-gold-master-publishing')&&bundle.includes('SKYWARD_POST_GOLD_MASTER'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/post-gold-master-publishing.json'));
check('docs F25 existem',fs.existsSync(path.join(root,'docs/REAL_DEVICE_QA_PLAN_F25.md'))&&fs.existsSync(path.join(root,'docs/SCREENSHOTS_FINAIS_F25.md'))&&fs.existsSync(path.join(root,'docs/BUG_REPORT_TEMPLATE_F25.md'))&&fs.existsSync(path.join(root,'docs/GITHUB_PAGES_PUBLICACAO_F25.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
check('GitHub Pages dados corretos',catalog.githubPages?.repo?.includes('ATC-SIMULADOR')&&catalog.githubPages?.localGitBashPath?.includes('ATC 3 NOVO'));
const run=spawnSync(process.execPath,['tests/phase25-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F25 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=14,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F25 disponíveis',['test:unit:f25','test:browser:f25','test:phase25'].every(k=>pkg.scripts?.[k]));check('npm test contém F25',String(pkg.scripts.test).includes('test:unit:f25')&&String(pkg.scripts.test).includes('test:browser:f25')&&String(pkg.scripts.test).includes('test:phase25'));}
const required=['src/runtime/28-post-gold-master-publishing.js','data/post-gold-master-publishing.json','tests/phase25-unit-tests.mjs','tests/phase25-browser-tests.py','tests/phase25-audit.mjs','docs/POST_GOLD_MASTER_PUBLICACAO_F25.md','docs/REAL_DEVICE_QA_PLAN_F25.md','docs/SCREENSHOTS_FINAIS_F25.md','docs/BUG_REPORT_TEMPLATE_F25.md','docs/GITHUB_PAGES_PUBLICACAO_F25.md','docs/FASE_25_CHECKLIST.md','docs/FASE_25_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE25_UNIT_TESTS.json','audit/PHASE25_BROWSER_TESTS.json'];check('artefatos F25 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F25 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
