import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE17_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE17_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/career-ratings.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F17',metadata.version==='1.17.0'&&metadata.phase==='F17');check('build oficial F17',/^SC-1\.17\.0-F17-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('career schema 1',metadata.careerSchema===1&&config.careerSchema===1);check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1);}
if(order&&runtime){check('arquitetura geração 17',runtime.architectureGeneration===17);check('26 módulos oficiais',order.modules.length>=26&&runtime.moduleCount===order.modules.length);check('módulo carreira antes de tráfego',order.modules.findIndex(m=>m.file==='20-controller-career.js')>=0&&order.modules.findIndex(m=>m.file==='20-controller-career.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F17 registrada',String(runtime.strategy).includes('deep-controller-career'));}
const source=read('src/runtime/20-controller-career.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F17 integrado',source.includes('CONTROLLER_CAREER_CATALOG')&&source.includes('window.SKYWARD_CAREER=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.licenses?.length>=6&&catalog.ratings?.length>=6&&catalog.shiftTypes?.length>=5);
check('carreira conectada ao início',traffic.includes('initializeCareerProfile'));
check('carreira conectada ao final',ui.includes('updateCareerAfterShift'));
check('UI final mostra carreira',ui.includes('Carreira')&&ui.includes('Fadiga'));
check('painel carreira no CSS',style.includes('.career-ops-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 20-controller-career')&&bundle.includes('SKYWARD_CAREER'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/career-ratings.json'));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
const run=spawnSync(process.execPath,['tests/phase17-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F17 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=16,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F17 disponíveis',['test:unit:f17','test:browser:f17','test:phase17'].every(k=>pkg.scripts?.[k]));check('npm test contém F17',String(pkg.scripts.test).includes('test:unit:f17')&&String(pkg.scripts.test).includes('test:browser:f17')&&String(pkg.scripts.test).includes('test:phase17'));}
const required=['src/runtime/20-controller-career.js','data/career-ratings.json','tests/phase17-unit-tests.mjs','tests/phase17-browser-tests.py','tests/phase17-audit.mjs','docs/CARREIRA_OPERACIONAL_PROFUNDA_F17.md','docs/FASE_17_CHECKLIST.md','docs/FASE_17_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE17_UNIT_TESTS.json','audit/PHASE17_BROWSER_TESTS.json'];check('artefatos F17 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F17 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
