import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const defaultRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const stageArg=process.argv.slice(2).find(a=>a.includes('SKYWARD_CONTROL_SC-')||a.endsWith('SKYWARD_CONTROL'));
const root=stageArg?path.resolve(stageArg):defaultRoot;const prepackage=process.argv.includes('--prepackage');
const read=r=>fs.readFileSync(path.join(root,r),'utf8'),json=r=>JSON.parse(read(r));const checks=[];const check=(n,o,d='')=>checks.push({name:n,ok:Boolean(o),detail:String(d||'')});
let metadata,config,order,runtime,unit,browser,pkg,catalog;for(const [n,r,s] of [['metadata','release-metadata.json',v=>metadata=v],['config','config/release.json',v=>config=v],['order','src/runtime/module-order.json',v=>order=v],['runtime','runtime-manifest.json',v=>runtime=v],['unit','audit/PHASE32_UNIT_TESTS.json',v=>unit=v],['browser','audit/PHASE32_BROWSER_TESTS.json',v=>browser=v],['package','package.json',v=>pkg=v],['catalog','data/airport-authority.json',v=>catalog=v]]){try{s(json(r));check(`${n} legível`,true);}catch(e){check(`${n} legível`,false,e.message);}}
if(metadata&&config){check('versão e fase F32',metadata.version==='1.32.0'&&metadata.phase==='F32');check('build oficial F32',/^SC-1\.32\.0-F32-\d{8}-\d{4}$/.test(metadata.build),metadata.build);check('airport authority schema 1',metadata.airportAuthoritySchema===1&&config.airportAuthoritySchema===1);check('canal airport-authority',metadata.channel==='airport-authority'&&config.channel==='airport-authority');check('schemas preservados',metadata.saveSchema===3&&metadata.contractSchema===2&&metadata.testSchema===3&&metadata.saveVaultSchema===1&&metadata.pwaSchema===1&&metadata.cacheSchema===1&&metadata.uxSchema===1&&metadata.desktopSchema===1&&metadata.accessibilitySchema===1&&metadata.replaySchema===1&&metadata.aircraftPerformanceSchema===1&&metadata.airportSurfaceSchema===1&&metadata.surfaceSafetySchema===1&&metadata.weatherOpsSchema===1&&metadata.procedureOpsSchema===1&&metadata.careerSchema===1&&metadata.economySchema===1&&metadata.incidentSchema===1&&metadata.networkFlowSchema===1&&metadata.controlRoomSchema===1&&metadata.commercialPolishSchema===1&&metadata.releaseCandidateSchema===1&&metadata.goldMasterSchema===1&&metadata.postGoldMasterSchema===1&&metadata.postPublishHealthSchema===1&&metadata.publicOpsSchema===1&&metadata.trainingAcademySchema===1&&metadata.trainingCoachSchema===1&&metadata.internationalCampaignSchema===1&&metadata.airlineOpsSchema===1);}
if(order&&runtime){check('arquitetura geração 32',runtime.architectureGeneration===32);check('41 módulos oficiais',order.modules.length>=41&&runtime.moduleCount===order.modules.length);check('módulo airport authority antes de tráfego',order.modules.findIndex(m=>m.file==='35-airport-authority-terminal-ops.js')>=0&&order.modules.findIndex(m=>m.file==='35-airport-authority-terminal-ops.js')<order.modules.findIndex(m=>m.file==='06-traffic-requests.js'));check('estratégia F32 registrada',String(runtime.strategy).includes('airport-authority-terminal-ops'));}
const source=read('src/runtime/35-airport-authority-terminal-ops.js'),bundle=read('main.js'),ui=read('src/runtime/09-ui-clearances.js'),traffic=read('src/runtime/06-traffic-requests.js'),style=read('style.css');
check('módulo F32 integrado',source.includes('AIRPORT_AUTHORITY_CATALOG')&&source.includes('window.SKYWARD_AIRPORT_AUTHORITY=Object.freeze'));
check('catálogo completo',catalog?.schema===1&&catalog.terminals?.length>=4&&catalog.gatePools?.length>=4&&catalog.passengerFlows?.length>=6);
check('F32 conectado ao início',traffic.includes('initializeAirportAuthority'));
check('UI final mostra Airport Auth',ui.includes('Airport Auth')&&ui.includes('Terminal EXP'));
check('CSS painel Airport Authority',style.includes('.airport-authority-inline'));
check('bundle sincronizado',bundle.includes('@skyward-module 35-airport-authority-terminal-ops')&&bundle.includes('SKYWARD_AIRPORT_AUTHORITY'));
check('PWA cache inclui catálogo',json('pwa-cache-manifest.json').files.some(f=>f.file==='data/airport-authority.json'));
check('docs F32 existem',fs.existsSync(path.join(root,'docs/AIRPORT_AUTHORITY_TERMINAL_OPS_F32.md'))&&fs.existsSync(path.join(root,'docs/TERMINAIS_PORTOES_PASSAGEIROS_F32.md')));
check('documento upload preservado',fs.existsSync(path.join(root,'UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md'))&&fs.existsSync(path.join(root,'docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md')));
check('documento upload contém caminhos',read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('/c/Users/jonat/Desktop/GAME/¨2026/ATC 3 NOVO')&&read('UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md').includes('https://github.com/jonatanoficial-bit/ATC-SIMULADOR.git'));
check('airport authority possui bagagem/conexões',catalog.passengerFlows.some(f=>f.id==='BAGGAGE')&&catalog.passengerFlows.some(f=>f.id==='CONNECTIONS'));
const run=spawnSync(process.execPath,['tests/phase32-unit-tests.mjs'],{cwd:root,encoding:'utf8'});check('unitários F32 executam novamente',run.status===0,(run.stderr||run.stdout).trim());
if(unit&&metadata){check('relatório unitário pertence à build',unit.build===metadata.build,`${unit.build} != ${metadata.build}`);check('unitários aprovados',unit.failed===0&&unit.passed===unit.total&&unit.total>=15,`${unit.passed}/${unit.total}`);}if(browser&&metadata){check('relatório browser pertence à build',browser.build?.build===metadata.build,`${browser.build?.build} != ${metadata.build}`);check('browser aprovado',browser.failed===0&&browser.passed===browser.total&&browser.total>=20,`${browser.passed}/${browser.total}`);check('quatro resoluções auditadas',['desktop','tablet','mobile_landscape','mobile_portrait'].every(n=>browser.viewports?.[n]));check('sem erros de console/página',(browser.consoleErrors||[]).length===0&&(browser.pageErrors||[]).length===0,JSON.stringify({console:browser.consoleErrors,page:browser.pageErrors}));}
if(pkg){check('scripts F32 disponíveis',['test:unit:f32','test:browser:f32','test:phase32'].every(k=>pkg.scripts?.[k]));check('npm test contém F32',String(pkg.scripts.test).includes('test:unit:f32')&&String(pkg.scripts.test).includes('test:browser:f32')&&String(pkg.scripts.test).includes('test:phase32'));}
const required=['src/runtime/35-airport-authority-terminal-ops.js','data/airport-authority.json','tests/phase32-unit-tests.mjs','tests/phase32-browser-tests.py','tests/phase32-audit.mjs','docs/AIRPORT_AUTHORITY_TERMINAL_OPS_F32.md','docs/TERMINAIS_PORTOES_PASSAGEIROS_F32.md','docs/FASE_32_CHECKLIST.md','docs/FASE_32_AUDITORIA.md','UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','docs/UPLOAD_GIT_BASH_CAMINHOS_ATC_SIMULADOR.md','audit/PHASE32_UNIT_TESTS.json','audit/PHASE32_BROWSER_TESTS.json'];check('artefatos F32 completos',required.every(r=>fs.existsSync(path.join(root,r))),required.filter(r=>!fs.existsSync(path.join(root,r))).join(', '));if(!prepackage)check('manifesto criptográfico presente',fs.existsSync(path.join(root,'MANIFEST_SHA256.txt')));
const failed=checks.filter(c=>!c.ok);console.log(`Skyward Control F32 audit: ${checks.length-failed.length}/${checks.length} aprovadas`);for(const c of checks)console.log(`${c.ok?'PASS':'FAIL'}  ${c.name}${!c.ok&&c.detail?` — ${c.detail}`:''}`);if(failed.length)process.exit(1);
