import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { ROOT, readJson } from './release-lib.mjs';

const args=new Set(process.argv.slice(2));
const checkOnly=args.has('--check');
const config=readJson(path.join(ROOT,'config/release.json'));
const fail=message=>{throw new Error(`PWA build: ${message}`);};
if(!config.build || !/^SC-\d+\.\d+\.\d+-F\d{2}-\d{8}-\d{4}$/.test(config.build)) fail('config/release.json precisa estar carimbado antes de gerar a PWA');
if(!Number.isInteger(config.pwaSchema)||config.pwaSchema<1) fail('pwaSchema inválido');
if(!Number.isInteger(config.cacheSchema)||config.cacheSchema<1) fail('cacheSchema inválido');

const manifest={
  id:'./',name:'Skyward Control — Simulador ATC',short_name:'Skyward Control',
  description:'Simulador de controle de tráfego aéreo mobile-first, instalável e disponível offline.',
  lang:'pt-BR',dir:'ltr',start_url:'./',scope:'./',display:'standalone',
  display_override:['fullscreen','standalone','minimal-ui'],orientation:'landscape',
  background_color:'#03060a',theme_color:'#05080d',categories:['games','education','simulation'],
  prefer_related_applications:false,
  icons:[
    {src:'assets/icons/icon-192.png',sizes:'192x192',type:'image/png',purpose:'any'},
    {src:'assets/icons/icon-512.png',sizes:'512x512',type:'image/png',purpose:'any'},
    {src:'assets/icons/icon-maskable-512.png',sizes:'512x512',type:'image/png',purpose:'maskable'}
  ]
};
const manifestText=JSON.stringify(manifest,null,2)+'\n';

const required=[
  'index.html','style.css','build-info.js','main.js','manifest.webmanifest',
  'data/airports.json','data/aircraft.json','data/aircraft-performance.json','data/airport-graphs.json','data/weather-profiles.json','data/procedures-f16.json','data/career-ratings.json','data/economy-contracts.json','data/incident-playbooks.json','data/network-flow-slots.json','data/control-room-ranking.json','data/ux-polish-presets.json','data/release-candidate-qa.json','data/gold-master-package.json','data/post-gold-master-publishing.json','data/post-publish-healthcheck.json','data/public-ops-feedback.json','data/training-academy-scenarios.json','data/training-coach-debriefing.json','data/international-campaign.json','data/airline-operations.json','data/airport-authority.json','data/crisis-command-center.json','data/safety-compliance-center.json','data/infrastructure-expansion.json','data/environment-sustainability.json','data/revenue-management.json','data/workforce-staffing.json','data/passenger-reputation.json','data/multi-airport-network.json','data/emergency-response-disaster.json','data/security-cyber-defense.json','data/asset-maintenance-reliability.json','data/digital-twin-predictive.json','data/ai-copilot-decision-support.json','data/radio-phraseology.json','data/ground-turnaround.json','data/cargo-logistics.json','data/terminal-flow.json','data/non-aero-revenue.json','data/adaptive-pace-workload.json','data/stability-diagnostics.json','data/pwa-update-manager.json','data/surface-hotspots.json',
  'assets/icons/icon-180.png','assets/icons/icon-192.png','assets/icons/icon-512.png','assets/icons/icon-maskable-512.png'
];
const collect=(dir,prefix='')=>{
  if(!fs.existsSync(dir))return [];
  return fs.readdirSync(dir,{withFileTypes:true}).flatMap(entry=>{
    const abs=path.join(dir,entry.name);const rel=path.posix.join(prefix,entry.name);
    return entry.isDirectory()?collect(abs,rel):entry.isFile()?[rel]:[];
  });
};
const assetFiles=collect(path.join(ROOT,'assets'),'assets').filter(rel=>/\.(?:png|jpg|jpeg|webp|svg)$/i.test(rel));
const files=[...new Set([...required,...assetFiles])].sort();
const sha256=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const cacheName=`skyward-control-${config.cacheSchema}-${String(config.build).toLowerCase()}`;

function generate(){
  // manifest must exist before hashing it.
  const manifestPath=path.join(ROOT,'manifest.webmanifest');
  const previous=fs.existsSync(manifestPath)?fs.readFileSync(manifestPath,'utf8'):null;
  if(!checkOnly) fs.writeFileSync(manifestPath,manifestText);
  else if(previous!==manifestText) fail('manifest.webmanifest desatualizado; execute npm run build:pwa');

  for(const rel of files) if(!fs.existsSync(path.join(ROOT,rel))) fail(`arquivo offline ausente: ${rel}`);
  const entries=files.map(rel=>({url:`./${rel}`,file:rel,bytes:fs.statSync(path.join(ROOT,rel)).size,sha256:sha256(path.join(ROOT,rel))}));
  const cacheManifest={schema:1,pwaSchema:config.pwaSchema,cacheSchema:config.cacheSchema,build:config.build,builtAt:config.builtAt,cacheName,scope:'./',strategy:'versioned-precache-controlled-update-network-first-navigation',files:entries};
  const cacheManifestText=JSON.stringify(cacheManifest,null,2)+'\n';
  const core=[...entries.map(item=>item.url),'./pwa-cache-manifest.json'];
  const sw=`/* AUTO-GENERATED by tools/build-pwa.mjs. Do not edit manually. */\n'use strict';\nconst PWA_META=Object.freeze(${JSON.stringify({schema:config.pwaSchema,cacheSchema:config.cacheSchema,build:config.build,cacheName})});\nconst CORE_ASSETS=Object.freeze(${JSON.stringify(core,null,2)});\nconst CACHE_PREFIX='skyward-control-';\nconst NAVIGATION_FALLBACK='./index.html';\nasync function openCurrentCache(){return caches.open(PWA_META.cacheName);}\nasync function precache(){const cache=await openCurrentCache();await cache.addAll(CORE_ASSETS);return true;}\nself.addEventListener('install',event=>{event.waitUntil((async()=>{await precache();if(!self.registration.active)await self.skipWaiting();})());});\nself.addEventListener('activate',event=>{event.waitUntil((async()=>{const names=await caches.keys();await Promise.all(names.filter(name=>name.startsWith(CACHE_PREFIX)&&name!==PWA_META.cacheName).map(name=>caches.delete(name)));await self.clients.claim();})());});\nself.addEventListener('message',event=>{const data=event.data||{};if(data.type==='SKIP_WAITING')self.skipWaiting();if(data.type==='GET_VERSION'){const reply={type:'PWA_VERSION',build:PWA_META.build,cacheName:PWA_META.cacheName,cacheReady:true};if(event.source&&event.source.postMessage)event.source.postMessage(reply);}});\nasync function navigationResponse(request){const cache=await openCurrentCache();try{const response=await fetch(request);if(response&&response.ok)cache.put(NAVIGATION_FALLBACK,response.clone());return response;}catch(_error){return (await cache.match(request,{ignoreSearch:true}))||(await cache.match(NAVIGATION_FALLBACK))||(await cache.match('./'));}}\nasync function cachedResponse(request){const cache=await openCurrentCache();const cached=await cache.match(request,{ignoreSearch:false});if(cached)return cached;try{const response=await fetch(request);if(response&&response.ok&&new URL(request.url).origin===self.location.origin)cache.put(request,response.clone());return response;}catch(_error){return new Response('',{status:503,statusText:'Offline'});}}\nself.addEventListener('fetch',event=>{const request=event.request;if(request.method!=='GET')return;const url=new URL(request.url);if(url.origin!==self.location.origin)return;if(request.mode==='navigate'){event.respondWith(navigationResponse(request));return;}event.respondWith(cachedResponse(request));});\n`;
  return {cacheManifestText,sw};
}
const generated=generate();
const outputs=[['pwa-cache-manifest.json',generated.cacheManifestText],['service-worker.js',generated.sw]];
if(checkOnly){
  for(const [rel,expected] of outputs){const file=path.join(ROOT,rel);if(!fs.existsSync(file)||fs.readFileSync(file,'utf8')!==expected)fail(`${rel} desatualizado; execute npm run build:pwa`);}
  console.log(`PWA check: ${files.length} arquivos, cache ${cacheName}`);
}else{
  for(const [rel,content] of outputs)fs.writeFileSync(path.join(ROOT,rel),content);
  console.log(`PWA built: ${files.length} arquivos, cache ${cacheName}`);
}
