import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

export const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
export const RELEASE_CONFIG = path.join(ROOT, 'config', 'release.json');

export function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

export function writeJson(file, value) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(value, null, 2) + '\n');
}

export function saoPauloStamp(date = new Date()) {
  const parts = Object.fromEntries(new Intl.DateTimeFormat('en-CA', {
    timeZone: 'America/Sao_Paulo', year: 'numeric', month: '2-digit', day: '2-digit',
    hour: '2-digit', minute: '2-digit', second: '2-digit', hourCycle: 'h23'
  }).formatToParts(date).filter(p => p.type !== 'literal').map(p => [p.type, p.value]));
  const compact = `${parts.year}${parts.month}${parts.day}-${parts.hour}${parts.minute}`;
  const display = `${parts.year}-${parts.month}-${parts.day} ${parts.hour}:${parts.minute} BRT`;
  const iso = `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}:${parts.second}-03:00`;
  return { compact, display, iso };
}

export function validateConfig(config) {
  const required = ['product','prefix','version','phase','phaseName','channel','saveSchema','contractSchema','testSchema','saveVaultSchema','pwaSchema','cacheSchema','uxSchema','desktopSchema','accessibilitySchema','replaySchema','target','timeZone'];
  for (const field of required) {
    if (config[field] === undefined || config[field] === null || config[field] === '') {
      throw new Error(`Campo obrigatório ausente em config/release.json: ${field}`);
    }
  }
  if (!/^\d+\.\d+\.\d+$/.test(config.version)) throw new Error('Versão deve seguir SemVer x.y.z');
  if (!/^F\d{2}$/.test(config.phase)) throw new Error('Fase deve seguir o padrão Fnn');
  if (!Number.isInteger(config.saveSchema) || config.saveSchema < 1) throw new Error('saveSchema inválido');
  if (!Number.isInteger(config.contractSchema) || config.contractSchema < 1) throw new Error('contractSchema inválido');
  if (!Number.isInteger(config.testSchema) || config.testSchema < 1) throw new Error('testSchema inválido');
  if (!Number.isInteger(config.saveVaultSchema) || config.saveVaultSchema < 1) throw new Error('saveVaultSchema inválido');
  if (!Number.isInteger(config.pwaSchema) || config.pwaSchema < 1) throw new Error('pwaSchema inválido');
  if (!Number.isInteger(config.cacheSchema) || config.cacheSchema < 1) throw new Error('cacheSchema inválido');
  if (!Number.isInteger(config.uxSchema) || config.uxSchema < 1) throw new Error('uxSchema inválido');
  if (!Number.isInteger(config.desktopSchema) || config.desktopSchema < 1) throw new Error('desktopSchema inválido');
  if (!Number.isInteger(config.accessibilitySchema) || config.accessibilitySchema < 1) throw new Error('accessibilitySchema inválido');
  if (!Number.isInteger(config.replaySchema) || config.replaySchema < 1) throw new Error('replaySchema inválido');
  if (config.aircraftPerformanceSchema !== undefined && (!Number.isInteger(config.aircraftPerformanceSchema) || config.aircraftPerformanceSchema < 1)) throw new Error('aircraftPerformanceSchema inválido');
  return true;
}

export function buildMetadata(config, date = new Date()) {
  validateConfig(config);
  const stamp = saoPauloStamp(date);
  const build = `${config.prefix}-${config.version}-${config.phase}-${stamp.compact}`;
  return { ...config, build, builtAt: stamp.display, builtAtIso: stamp.iso };
}

export function writeGeneratedFiles(root, metadata) {
  const runtime = {
    product: metadata.product,
    version: metadata.version,
    phase: metadata.phase,
    phaseName: metadata.phaseName,
    channel: metadata.channel,
    build: metadata.build,
    builtAt: metadata.builtAt,
    builtAtIso: metadata.builtAtIso,
    schema: metadata.saveSchema,
    contractSchema: metadata.contractSchema,
    testSchema: metadata.testSchema,
    saveVaultSchema: metadata.saveVaultSchema,
    pwaSchema: metadata.pwaSchema,
    cacheSchema: metadata.cacheSchema,
    uxSchema: metadata.uxSchema,
    desktopSchema: metadata.desktopSchema,
    accessibilitySchema: metadata.accessibilitySchema,
    replaySchema: metadata.replaySchema,
    aircraftPerformanceSchema: metadata.aircraftPerformanceSchema || 1,
    target: metadata.target
  };
  fs.writeFileSync(path.join(root, 'build-info.js'),
    `/* AUTO-GENERATED by tools/release.mjs. Do not edit manually. */\nwindow.SKYWARD_BUILD_INFO = Object.freeze(${JSON.stringify(runtime, null, 2)});\n`);
  writeJson(path.join(root, 'release-metadata.json'), metadata);
  fs.writeFileSync(path.join(root, 'version.txt'), [
    metadata.product.toUpperCase(),
    `Version: ${metadata.version}`,
    `Phase: ${metadata.phase} — ${metadata.phaseName}`,
    `Build: ${metadata.build}`,
    `Built at: ${metadata.builtAt}`,
    `Channel: ${metadata.channel}`,
    `Save schema: ${metadata.saveSchema}`,
    `Contract schema: ${metadata.contractSchema}`,
    `Test schema: ${metadata.testSchema}`,
    `Save vault schema: ${metadata.saveVaultSchema}`,
    `PWA schema: ${metadata.pwaSchema}`,
    `Cache schema: ${metadata.cacheSchema}`,
    `UX schema: ${metadata.uxSchema}`,
    `Desktop schema: ${metadata.desktopSchema}`,
    `Accessibility schema: ${metadata.accessibilitySchema}`,
    `Replay schema: ${metadata.replaySchema}`,
    `Aircraft performance schema: ${metadata.aircraftPerformanceSchema || 1}`,
    `Target: ${metadata.target}`, 
    ''
  ].join('\n'));
  const packagePath = path.join(root, 'package.json');
  if (fs.existsSync(packagePath)) {
    const packageJson = readJson(packagePath);
    packageJson.version = metadata.version;
    writeJson(packagePath, packageJson);
  }

  fs.writeFileSync(path.join(root, 'RELEASE.txt'), [
    metadata.product.toUpperCase(),
    `Commercial evolution program — Phase ${metadata.phase.slice(1)}`,
    `Version: ${metadata.version}`,
    `Build: ${metadata.build}`,
    `Built: ${metadata.builtAt}`,
    `Channel: ${metadata.channel.toUpperCase()}`,
    `Status: ${metadata.phase} AUDITED / RELEASE PIPELINE LOCKED`,
    ''
  ].join('\n'));
  fs.writeFileSync(path.join(root, 'BUILD_NOTES.md'), `# Build Notes — ${metadata.build}\n\n## Identificação\n\n- Produto: ${metadata.product}\n- Versão: ${metadata.version}\n- Fase: ${metadata.phase} — ${metadata.phaseName}\n- Build: \`${metadata.build}\`\n- Data/hora: ${metadata.builtAt}\n- Canal: ${metadata.channel}\n- Save schema: ${metadata.saveSchema}\n- Contract schema: ${metadata.contractSchema}\n- Test schema: ${metadata.testSchema}\n- Save vault schema: ${metadata.saveVaultSchema}\n- PWA schema: ${metadata.pwaSchema}\n- Cache schema: ${metadata.cacheSchema}\n- UX schema: ${metadata.uxSchema}\n- Alvo: ${metadata.target}\n\n## Geração reproduzível\n\nA identificação desta build é gerada a partir de \`config/release.json\`. Não edite \`build-info.js\`, \`release-metadata.json\`, \`version.txt\`, \`RELEASE.txt\` ou este arquivo manualmente.\n\nExecute:\n\n\`\`\`bash\nnpm run release -- --version ${metadata.version} --phase ${metadata.phase} --phase-name "${metadata.phaseName}"\n\`\`\`\n\nPara validar uma build já empacotada:\n\n\`\`\`bash\nnpm test\nnpm run verify:integrity\n\`\`\`\n\n## Compatibilidade mantida\n\n- Celular horizontal: 844 × 390\n- Celular vertical: 390 × 844 nos menus; orientação horizontal durante o turno\n- Tablet: 1024 × 768\n- PC: 1440 × 900\n\n## Política anti-quebra\n\nA geração é interrompida quando há divergência de metadados, TypeScript inválido, contratos desatualizados, JavaScript inválido, JSON corrompido, referência de asset ausente, arquivo obrigatório faltando ou teste unitário reprovado, cenário Chromium reprovado, soak test instável ou teste de regressão reprovado. O pacote final recebe manifesto SHA-256 interno e checksum externo do ZIP.\n`);

  const historyPath = path.join(root, 'BUILD_HISTORY.json');
  let history = [];
  if (fs.existsSync(historyPath)) {
    try { history = readJson(historyPath); } catch { history = []; }
  }
  history = Array.isArray(history) ? history.filter(item => item.build !== metadata.build) : [];
  history.unshift({
    build: metadata.build, version: metadata.version, phase: metadata.phase,
    phaseName: metadata.phaseName, builtAt: metadata.builtAt,
    builtAtIso: metadata.builtAtIso, channel: metadata.channel, saveSchema: metadata.saveSchema, contractSchema: metadata.contractSchema, testSchema: metadata.testSchema, saveVaultSchema: metadata.saveVaultSchema, pwaSchema: metadata.pwaSchema, cacheSchema: metadata.cacheSchema, uxSchema: metadata.uxSchema, desktopSchema: metadata.desktopSchema, accessibilitySchema: metadata.accessibilitySchema, replaySchema: metadata.replaySchema
  });
  writeJson(historyPath, history.slice(0, 100));
}

export function sha256(file) {
  return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
}

export function listFiles(root, exclusions = []) {
  const result = [];
  const walk = dir => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const abs = path.join(dir, entry.name);
      const rel = path.relative(root, abs).replaceAll(path.sep, '/');
      if (exclusions.some(rule => rel === rule || rel.startsWith(`${rule}/`))) continue;
      if (entry.isDirectory()) walk(abs);
      else if (entry.isFile()) result.push(rel);
    }
  };
  walk(root);
  return result.sort();
}

export function writeManifest(root) {
  const exclusions = ['MANIFEST_SHA256.txt', 'dist', 'node_modules', '.git'];
  const files = listFiles(root, exclusions);
  const lines = files.map(rel => `${sha256(path.join(root, rel))}  ${rel}`);
  fs.writeFileSync(path.join(root, 'MANIFEST_SHA256.txt'), lines.join('\n') + '\n');
  return lines.length;
}
